/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import {
  AiPoweredScanFinding,
  aiPoweredScanFindingSchema,
} from '../aiPoweredScanFinding.js';
import { SastFinding, sastFindingSchema } from '../sastFinding.js';
import { ScaFinding, scaFindingSchema } from '../scaFinding.js';

/** This is a container type for one-of types. */
export type ApiV1DeploymentsFindingsResponseFindings =
  | SastFinding
  | ScaFinding
  | AiPoweredScanFinding;

export const apiV1DeploymentsFindingsResponseFindingsSchema: Schema<ApiV1DeploymentsFindingsResponseFindings> = lazy(
  () => oneOf([sastFindingSchema, scaFindingSchema, aiPoweredScanFindingSchema])
);

export namespace ApiV1DeploymentsFindingsResponseFindings {
  /**
   * Validation method to narrow down union type to SastFinding type case.
   *
   * This is Sast Finding case.
   */
  export function isSastFinding(value: unknown): value is SastFinding {
    return isMappedValueValidForSchema(value, sastFindingSchema);
  }

  /**
   * Validation method to narrow down union type to ScaFinding type case.
   *
   * This is Sca Finding case.
   */
  export function isScaFinding(value: unknown): value is ScaFinding {
    return isMappedValueValidForSchema(value, scaFindingSchema);
  }

  /**
   * Validation method to narrow down union type to AiPoweredScanFinding type case.
   *
   * This is AI-Powered Scan Finding case.
   */
  export function isAiPoweredScanFinding(
    value: unknown
  ): value is AiPoweredScanFinding {
    return isMappedValueValidForSchema(value, aiPoweredScanFindingSchema);
  }
}
