/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ProtosOpenapiV1ListDeploymentsResponse,
  protosOpenapiV1ListDeploymentsResponseSchema,
} from '../models/protosOpenapiV1ListDeploymentsResponse.js';
import { BaseApi } from './baseApi.js';

export class DeploymentsServiceApi extends BaseApi {
  /**
   * Request the deployments your auth can access.
   *
   * Currently available auth scope does not extend over more than one deployment. This endpoint returns
   * the single deployment your token can access. The endpoint additionally returns links to related
   * resources available on this API.
   *
   * @return Response from the API call
   */
  async deploymentsServiceListDeployments(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ProtosOpenapiV1ListDeploymentsResponse>> {
    const req = this.createRequest('GET', '/api/v1/deployments');
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(
      protosOpenapiV1ListDeploymentsResponseSchema,
      requestOptions
    );
  }
}
