/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ApiV1DeploymentsFindingsResponse,
  apiV1DeploymentsFindingsResponseSchema,
} from '../models/apiV1DeploymentsFindingsResponse.js';
import {
  AutotriageVerdict2,
  autotriageVerdict2Schema,
} from '../models/autotriageVerdict2.js';
import {
  ClickToFixPrState,
  clickToFixPrStateSchema,
} from '../models/clickToFixPrState.js';
import { Confidence8, confidence8Schema } from '../models/confidence8.js';
import { Exposures2, exposures2Schema } from '../models/exposures2.js';
import { IssueType2, issueType2Schema } from '../models/issueType2.js';
import { Severities2, severities2Schema } from '../models/severities2.js';
import { Status9, status9Schema } from '../models/status9.js';
import {
  Transitivities2,
  transitivities2Schema,
} from '../models/transitivities2.js';
import {
  TriageReasons2,
  triageReasons2Schema,
} from '../models/triageReasons2.js';
import { array, bigint, boolean, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class FindingsServiceApi extends BaseApi {
  /**
   * Request the list of code, supply chain, or AI-powered scan findings in an organization, paginated in
   * pages of 100 entries and limited by the `since` timestamp. Findings are returned by `relevant_since`
   * descending (see `since` in the Query Parameters list). Examples: List SAST findings with pagination,
   * List SCA findings since timestamp, List AI-powered scan findings, List findings with filters.
   *
   * @param deploymentSlug
   * @param issueType             Example: sast
   * @param since
   * @param page                  Example: 0
   * @param dedup                 Example: false
   * @param pageSize              Example: 100
   * @param repos
   * @param repositoryIds
   * @param status
   * @param triageReasons
   * @param severities
   * @param ref
   * @param policies
   * @param rules
   * @param categories
   * @param confidence
   * @param autotriageVerdict
   * @param componentTags
   * @param exposures
   * @param transitivities
   * @param isMalicious
   * @param clickToFixPrState
   * @return Response from the API call
   */
  async findingsServiceListFindings(
    deploymentSlug: string,
    issueType?: IssueType2,
    since?: number,
    page?: bigint,
    dedup?: boolean,
    pageSize?: bigint,
    repos?: string[],
    repositoryIds?: bigint[],
    status?: Status9,
    triageReasons?: TriageReasons2,
    severities?: Severities2,
    ref?: string,
    policies?: string[],
    rules?: string[],
    categories?: string[],
    confidence?: Confidence8,
    autotriageVerdict?: AutotriageVerdict2,
    componentTags?: string[],
    exposures?: Exposures2,
    transitivities?: Transitivities2,
    isMalicious?: boolean,
    clickToFixPrState?: ClickToFixPrState,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ApiV1DeploymentsFindingsResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      deploymentSlug: [deploymentSlug, string()],
      issueType: [issueType, optional(issueType2Schema)],
      since: [since, optional(number())],
      page: [page, optional(bigint())],
      dedup: [dedup, optional(boolean())],
      pageSize: [pageSize, optional(bigint())],
      repos: [repos, optional(array(string()))],
      repositoryIds: [repositoryIds, optional(array(bigint()))],
      status: [status, optional(status9Schema)],
      triageReasons: [triageReasons, optional(triageReasons2Schema)],
      severities: [severities, optional(severities2Schema)],
      ref: [ref, optional(string())],
      policies: [policies, optional(array(string()))],
      rules: [rules, optional(array(string()))],
      categories: [categories, optional(array(string()))],
      confidence: [confidence, optional(confidence8Schema)],
      autotriageVerdict: [
        autotriageVerdict,
        optional(autotriageVerdict2Schema),
      ],
      componentTags: [componentTags, optional(array(string()))],
      exposures: [exposures, optional(exposures2Schema)],
      transitivities: [transitivities, optional(transitivities2Schema)],
      isMalicious: [isMalicious, optional(boolean())],
      clickToFixPrState: [clickToFixPrState, optional(clickToFixPrStateSchema)],
    });
    req.query('issue_type', mapped.issueType);
    req.query('since', mapped.since);
    req.query('page', mapped.page);
    req.query('dedup', mapped.dedup);
    req.query('page_size', mapped.pageSize);
    req.query('repos', mapped.repos);
    req.query('repository_ids', mapped.repositoryIds);
    req.query('status', mapped.status);
    req.query('triage_reasons', mapped.triageReasons);
    req.query('severities', mapped.severities);
    req.query('ref', mapped.ref);
    req.query('policies', mapped.policies);
    req.query('rules', mapped.rules);
    req.query('categories', mapped.categories);
    req.query('confidence', mapped.confidence);
    req.query('autotriage_verdict', mapped.autotriageVerdict);
    req.query('component_tags', mapped.componentTags);
    req.query('exposures', mapped.exposures);
    req.query('transitivities', mapped.transitivities);
    req.query('is_malicious', mapped.isMalicious);
    req.query('click_to_fix_pr_state', mapped.clickToFixPrState);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentSlug}/findings`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(
      apiV1DeploymentsFindingsResponseSchema,
      requestOptions
    );
  }
}
