/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ProtosOpenapiV1GetBootstrapSmsVpcResponse,
  protosOpenapiV1GetBootstrapSmsVpcResponseSchema,
} from '../models/protosOpenapiV1GetBootstrapSmsVpcResponse.js';
import { optional, unknown } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class MiscServiceApi extends BaseApi {
  /**
   * VPC support for Managed Scans is in private beta.
   *
   * Returns the Managed Scans VPC Bootstrap CloudFormation template in JSON format for setting up cross-
   * account infrastructure.
   *
   * This template creates IAM roles and policies needed for Semgrep Managed Scanning (SMS) VPC
   * infrastructure automation,
   * including the semgrep-sms-vpc-automation role and EC2 Image Builder distribution roles for gVisor
   * container runtime.
   *
   * See the original AWS cloudformation template format at https://docs.aws.amazon.
   * com/AWSCloudFormation/latest/UserGuide/template-formats.html
   *
   *
   * @return Response from the API call
   */
  async miscServiceGetBootstrapSmsVpc(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ProtosOpenapiV1GetBootstrapSmsVpcResponse>> {
    const req = this.createRequest('GET', '/api/v1/bootstrap-sms-vpc');
    req.authenticate([]);
    return req.callAsJson(
      protosOpenapiV1GetBootstrapSmsVpcResponseSchema,
      requestOptions
    );
  }

  /**
   * Use to ping the server and assert liveness.
   *
   * @return Response from the API call
   */
  async miscServicePing(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown | undefined>> {
    const req = this.createRequest('GET', '/api/v1/ping');
    req.authenticate([]);
    return req.callAsJson(optional(unknown()), requestOptions);
  }
}
