/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ProtosOpenapiV1ListPoliciesResponse,
  protosOpenapiV1ListPoliciesResponseSchema,
} from '../models/protosOpenapiV1ListPoliciesResponse.js';
import {
  ProtosOpenapiV1ListPolicyRulesResponse,
  protosOpenapiV1ListPolicyRulesResponseSchema,
} from '../models/protosOpenapiV1ListPolicyRulesResponse.js';
import {
  ProtosOpenapiV1UpdatePolicyResponse,
  protosOpenapiV1UpdatePolicyResponseSchema,
} from '../models/protosOpenapiV1UpdatePolicyResponse.js';
import {
  UpdatePolicyRequest,
  updatePolicyRequestSchema,
} from '../models/updatePolicyRequest.js';
import { bigint, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class PoliciesServiceApi extends BaseApi {
  /**
   * @param deploymentId
   * @return Response from the API call
   */
  async policiesServiceListPolicies(
    deploymentId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ProtosOpenapiV1ListPoliciesResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ deploymentId: [deploymentId, string()] });
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentId}/policies`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(
      protosOpenapiV1ListPoliciesResponseSchema,
      requestOptions
    );
  }

  /**
   * @param deploymentId
   * @param policyId
   * @param cursor
   * @param limit
   * @return Response from the API call
   */
  async policiesServiceListPolicyRules(
    deploymentId: string,
    policyId: string,
    cursor?: string,
    limit?: bigint,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ProtosOpenapiV1ListPolicyRulesResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      deploymentId: [deploymentId, string()],
      policyId: [policyId, string()],
      cursor: [cursor, optional(string())],
      limit: [limit, optional(bigint())],
    });
    req.query('cursor', mapped.cursor);
    req.query('limit', mapped.limit);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentId}/policies/${mapped.policyId}`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(
      protosOpenapiV1ListPolicyRulesResponseSchema,
      requestOptions
    );
  }

  /**
   * @param deploymentId
   * @param policyId
   * @param body
   * @return Response from the API call
   */
  async policiesServiceUpdatePolicy(
    deploymentId: string,
    policyId: string,
    body: UpdatePolicyRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ProtosOpenapiV1UpdatePolicyResponse>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      deploymentId: [deploymentId, string()],
      policyId: [policyId, string()],
      body: [body, updatePolicyRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentId}/policies/${mapped.policyId}`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(
      protosOpenapiV1UpdatePolicyResponseSchema,
      requestOptions
    );
  }
}
