/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AddProjectTagsRequest,
  addProjectTagsRequestSchema,
} from '../models/addProjectTagsRequest.js';
import {
  AddProjectTagsResponse,
  addProjectTagsResponseSchema,
} from '../models/addProjectTagsResponse.js';
import {
  DeleteProjectResponse,
  deleteProjectResponseSchema,
} from '../models/deleteProjectResponse.js';
import {
  DeleteProjectTagsResponse,
  deleteProjectTagsResponseSchema,
} from '../models/deleteProjectTagsResponse.js';
import {
  GetProjectResponse,
  getProjectResponseSchema,
} from '../models/getProjectResponse.js';
import {
  ListProjectsResponse,
  listProjectsResponseSchema,
} from '../models/listProjectsResponse.js';
import {
  ToggleProjectManagedScanRequest,
  toggleProjectManagedScanRequestSchema,
} from '../models/toggleProjectManagedScanRequest.js';
import {
  ToggleProjectManagedScanResponse,
  toggleProjectManagedScanResponseSchema,
} from '../models/toggleProjectManagedScanResponse.js';
import {
  UpdateProjectRequest,
  updateProjectRequestSchema,
} from '../models/updateProjectRequest.js';
import {
  UpdateProjectResponse,
  updateProjectResponseSchema,
} from '../models/updateProjectResponse.js';
import { array, bigint, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class ProjectsServiceApi extends BaseApi {
  /**
   * Request the list of projects that have been scanned or onboarded to Managed Scans. Does not return
   * archived repositories. Returns 100 projects per page by default.
   *
   * @param deploymentSlug
   * @param page
   * @param pageSize       Example: 100
   * @return Response from the API call
   */
  async projectsServiceListProjects(
    deploymentSlug: string,
    page?: bigint,
    pageSize?: bigint,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListProjectsResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      deploymentSlug: [deploymentSlug, string()],
      page: [page, optional(bigint())],
      pageSize: [pageSize, optional(bigint())],
    });
    req.query('page', mapped.page);
    req.query('page_size', mapped.pageSize);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentSlug}/projects`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(listProjectsResponseSchema, requestOptions);
  }

  /**
   * Delete a project for a deployment you have access to. This will also delete all of the associated
   * findings.
   *
   * @param deploymentSlug
   * @param projectName
   * @return Response from the API call
   */
  async projectsServiceDeleteProject(
    deploymentSlug: string,
    projectName: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeleteProjectResponse>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      deploymentSlug: [deploymentSlug, string()],
      projectName: [projectName, string()],
    });
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentSlug}/projects/${mapped.projectName}`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(deleteProjectResponseSchema, requestOptions);
  }

  /**
   * Retrieve details for a single project associated with a deployment that you have access to.
   *
   * @param deploymentSlug
   * @param projectName
   * @return Response from the API call
   */
  async projectsServiceGetProject(
    deploymentSlug: string,
    projectName: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetProjectResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      deploymentSlug: [deploymentSlug, string()],
      projectName: [projectName, string()],
    });
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentSlug}/projects/${mapped.projectName}`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(getProjectResponseSchema, requestOptions);
  }

  /**
   * Update attributes for the project using the value passed in to the request body.
   *
   * Note: The only attribute that is supported as of January 2023 is `tags`.
   *
   * @param deploymentSlug
   * @param projectName
   * @param body
   * @return Response from the API call
   */
  async projectsServiceUpdateProject(
    deploymentSlug: string,
    projectName: string,
    body: UpdateProjectRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UpdateProjectResponse>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      deploymentSlug: [deploymentSlug, string()],
      projectName: [projectName, string()],
      body: [body, updateProjectRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentSlug}/projects/${mapped.projectName}`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(updateProjectResponseSchema, requestOptions);
  }

  /**
   * Enable or disable
   * [Semgrep Managed Scans](/docs/deployment/managed-scanning/overview)
   * for a project.
   *
   * @param deploymentSlug
   * @param projectName
   * @param body
   * @return Response from the API call
   */
  async projectsServiceToggleProjectManagedScan(
    deploymentSlug: string,
    projectName: string,
    body: ToggleProjectManagedScanRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ToggleProjectManagedScanResponse>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      deploymentSlug: [deploymentSlug, string()],
      projectName: [projectName, string()],
      body: [body, toggleProjectManagedScanRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentSlug}/projects/${mapped.projectName}/managed-scan`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(
      toggleProjectManagedScanResponseSchema,
      requestOptions
    );
  }

  /**
   * Remove tags from a project for a deployment you have access to.
   *
   * This request will not delete project tags from the deployment and will only remove
   * them from the requested project. Any other projects associated with the requested
   * tag will remain unaffected.
   *
   * @param deploymentSlug
   * @param projectName
   * @param tags
   * @return Response from the API call
   */
  async projectsServiceDeleteProjectTags(
    deploymentSlug: string,
    projectName: string,
    tags?: string[],
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DeleteProjectTagsResponse>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      deploymentSlug: [deploymentSlug, string()],
      projectName: [projectName, string()],
      tags: [tags, optional(array(string()))],
    });
    req.query('tags', mapped.tags);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentSlug}/projects/${mapped.projectName}/tags`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(deleteProjectTagsResponseSchema, requestOptions);
  }

  /**
   * Add tags to a project for a deployment you have access to.
   *
   * Any project tags that do not already exist for the deployment will be created automatically and
   * associated with the project.
   *
   * @param deploymentSlug
   * @param projectName
   * @param body
   * @return Response from the API call
   */
  async projectsServiceAddProjectTags(
    deploymentSlug: string,
    projectName: string,
    body: AddProjectTagsRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AddProjectTagsResponse>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      deploymentSlug: [deploymentSlug, string()],
      projectName: [projectName, string()],
      body: [body, addProjectTagsRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentSlug}/projects/${mapped.projectName}/tags`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(addProjectTagsResponseSchema, requestOptions);
  }
}
