/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ProtosOpenapiV1GetScanResponse,
  protosOpenapiV1GetScanResponseSchema,
} from '../models/protosOpenapiV1GetScanResponse.js';
import {
  ProtosOpenapiV1SearchScansResponse,
  protosOpenapiV1SearchScansResponseSchema,
} from '../models/protosOpenapiV1SearchScansResponse.js';
import {
  SearchScansRequest,
  searchScansRequestSchema,
} from '../models/searchScansRequest.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class ScansServiceApi extends BaseApi {
  /**
   * Request the details of a scan including the associated deployment, repository, and commit
   * information.
   *
   * @param deploymentId
   * @param scanId
   * @return Response from the API call
   */
  async scansServiceGetScan(
    deploymentId: string,
    scanId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ProtosOpenapiV1GetScanResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      deploymentId: [deploymentId, string()],
      scanId: [scanId, string()],
    });
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentId}/scan/${mapped.scanId}`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(protosOpenapiV1GetScanResponseSchema, requestOptions);
  }

  /**
   * List the scans associated with a particular repository over the past 30 days.
   *
   * @param deploymentId
   * @param body
   * @return Response from the API call
   */
  async scansServiceSearchScans(
    deploymentId: string,
    body: SearchScansRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ProtosOpenapiV1SearchScansResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      deploymentId: [deploymentId, string()],
      body: [body, searchScansRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentId}/scans/search`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(
      protosOpenapiV1SearchScansResponseSchema,
      requestOptions
    );
  }
}
