/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ProtosOpenapiV1ListSecretsPathResponse,
  protosOpenapiV1ListSecretsPathResponseSchema,
} from '../models/protosOpenapiV1ListSecretsPathResponse.js';
import { Severity5, severity5Schema } from '../models/severity5.js';
import { Status8, status8Schema } from '../models/status8.js';
import {
  ValidationState3,
  validationState3Schema,
} from '../models/validationState3.js';
import { array, bigint, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class SecretsServiceApi extends BaseApi {
  /**
   * @param deploymentId
   * @param cursor
   * @param limit
   * @param since
   * @param validationState
   * @param status          Example: FINDING_STATUS_UNSPECIFIED
   * @param severity
   * @param repo
   * @return Response from the API call
   */
  async secretsServiceListSecretsPath(
    deploymentId: string,
    cursor?: string,
    limit?: bigint,
    since?: string,
    validationState?: ValidationState3[],
    status?: Status8,
    severity?: Severity5[],
    repo?: string[],
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ProtosOpenapiV1ListSecretsPathResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      deploymentId: [deploymentId, string()],
      cursor: [cursor, optional(string())],
      limit: [limit, optional(bigint())],
      since: [since, optional(string())],
      validationState: [
        validationState,
        optional(array(validationState3Schema)),
      ],
      status: [status, optional(status8Schema)],
      severity: [severity, optional(array(severity5Schema))],
      repo: [repo, optional(array(string()))],
    });
    req.query('cursor', mapped.cursor);
    req.query('limit', mapped.limit);
    req.query('since', mapped.since);
    req.query('validationState', mapped.validationState);
    req.query('status', mapped.status);
    req.query('severity', mapped.severity);
    req.query('repo', mapped.repo);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentId}/secrets`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(
      protosOpenapiV1ListSecretsPathResponseSchema,
      requestOptions
    );
  }
}
