/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CreateSbomExportRequest,
  createSbomExportRequestSchema,
} from '../models/createSbomExportRequest.js';
import {
  CreateSbomExportResponse,
  createSbomExportResponseSchema,
} from '../models/createSbomExportResponse.js';
import {
  GetSbomExportResponse,
  getSbomExportResponseSchema,
} from '../models/getSbomExportResponse.js';
import {
  ListDependenciesRequest,
  listDependenciesRequestSchema,
} from '../models/listDependenciesRequest.js';
import {
  ListDependenciesResponse,
  listDependenciesResponseSchema,
} from '../models/listDependenciesResponse.js';
import {
  ListLockfilesForDependenciesRequest,
  listLockfilesForDependenciesRequestSchema,
} from '../models/listLockfilesForDependenciesRequest.js';
import {
  ListLockfilesForDependenciesResponse,
  listLockfilesForDependenciesResponseSchema,
} from '../models/listLockfilesForDependenciesResponse.js';
import {
  ListRepositoriesForDependenciesRequest,
  listRepositoriesForDependenciesRequestSchema,
} from '../models/listRepositoriesForDependenciesRequest.js';
import {
  ListRepositoriesForDependenciesResponse,
  listRepositoriesForDependenciesResponseSchema,
} from '../models/listRepositoriesForDependenciesResponse.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class SupplyChainServiceApi extends BaseApi {
  /**
   * @param deploymentId
   * @param body
   * @return Response from the API call
   */
  async listDependencies(
    deploymentId: string,
    body: ListDependenciesRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListDependenciesResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      deploymentId: [deploymentId, string()],
      body: [body, listDependenciesRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentId}/dependencies`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(listDependenciesResponseSchema, requestOptions);
  }

  /**
   * @param deploymentId
   * @param body
   * @return Response from the API call
   */
  async listRepositoriesForDependencies(
    deploymentId: string,
    body: ListRepositoriesForDependenciesRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListRepositoriesForDependenciesResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      deploymentId: [deploymentId, string()],
      body: [body, listRepositoriesForDependenciesRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentId}/dependencies/repositories`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(
      listRepositoriesForDependenciesResponseSchema,
      requestOptions
    );
  }

  /**
   * @param deploymentId
   * @param repositoryId
   * @param body
   * @return Response from the API call
   */
  async listLockfilesForDependencies(
    deploymentId: string,
    repositoryId: string,
    body: ListLockfilesForDependenciesRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListLockfilesForDependenciesResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      deploymentId: [deploymentId, string()],
      repositoryId: [repositoryId, string()],
      body: [body, listLockfilesForDependenciesRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentId}/dependencies/repositories/${mapped.repositoryId}/lockfiles`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(
      listLockfilesForDependenciesResponseSchema,
      requestOptions
    );
  }

  /**
   * @param deploymentId
   * @param body
   * @return Response from the API call
   */
  async createSbomExport(
    deploymentId: string,
    body: CreateSbomExportRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreateSbomExportResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      deploymentId: [deploymentId, string()],
      body: [body, createSbomExportRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentId}/sbom/export`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(createSbomExportResponseSchema, requestOptions);
  }

  /**
   * @param deploymentId
   * @param taskToken
   * @return Response from the API call
   */
  async getSbomExport(
    deploymentId: string,
    taskToken: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetSbomExportResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      deploymentId: [deploymentId, string()],
      taskToken: [taskToken, string()],
    });
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentId}/sbom/export/${mapped.taskToken}`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(getSbomExportResponseSchema, requestOptions);
  }
}
