/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CreateTicketRequest,
  createTicketRequestSchema,
} from '../models/createTicketRequest.js';
import {
  LinkTicketRequest,
  linkTicketRequestSchema,
} from '../models/linkTicketRequest.js';
import {
  ProtosOpenapiV1CreateTicketResponse,
  protosOpenapiV1CreateTicketResponseSchema,
} from '../models/protosOpenapiV1CreateTicketResponse.js';
import {
  ProtosOpenapiV1DeleteTicketResponse,
  protosOpenapiV1DeleteTicketResponseSchema,
} from '../models/protosOpenapiV1DeleteTicketResponse.js';
import {
  ProtosOpenapiV1LinkTicketResponse,
  protosOpenapiV1LinkTicketResponseSchema,
} from '../models/protosOpenapiV1LinkTicketResponse.js';
import {
  ProtosOpenapiV1UnlinkTicketResponse,
  protosOpenapiV1UnlinkTicketResponseSchema,
} from '../models/protosOpenapiV1UnlinkTicketResponse.js';
import {
  UnlinkTicketRequest,
  unlinkTicketRequestSchema,
} from '../models/unlinkTicketRequest.js';
import { bigint, string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class TicketingServiceApi extends BaseApi {
  /**
   * Unlink a Jira ticket by its ID
   *
   * @param deploymentId
   * @param externalTicketId
   * @return Response from the API call
   */
  async deleteTicket(
    deploymentId: string,
    externalTicketId: bigint,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ProtosOpenapiV1DeleteTicketResponse>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      deploymentId: [deploymentId, string()],
      externalTicketId: [externalTicketId, bigint()],
    });
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentId}/ticketing/v2/tickets/${mapped.externalTicketId}`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(
      protosOpenapiV1DeleteTicketResponseSchema,
      requestOptions
    );
  }

  /**
   * Link an existing external ticket (e.g. Jira) to one or more Semgrep findings by providing the ticket
   * URL and a list of finding IDs. This does not create a ticket in your issue tracker — it only records
   * the association in Semgrep. If a finding is already linked to a different ticket, the existing link
   * is replaced. Requires a configured ticketing integration.
   *
   * @param deploymentId
   * @param body
   * @return Response from the API call
   */
  async linkTicket(
    deploymentId: string,
    body: LinkTicketRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ProtosOpenapiV1LinkTicketResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      deploymentId: [deploymentId, string()],
      body: [body, linkTicketRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentId}/tickets/link`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(
      protosOpenapiV1LinkTicketResponseSchema,
      requestOptions
    );
  }

  /**
   * Remove the ticket association from one or more Semgrep findings by providing a list of finding IDs.
   * This does not delete the ticket in your issue tracker — it only removes the association in Semgrep.
   *
   * @param deploymentId
   * @param body
   * @return Response from the API call
   */
  async unlinkTicket(
    deploymentId: string,
    body: UnlinkTicketRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ProtosOpenapiV1UnlinkTicketResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      deploymentId: [deploymentId, string()],
      body: [body, unlinkTicketRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentId}/tickets/unlink`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(
      protosOpenapiV1UnlinkTicketResponseSchema,
      requestOptions
    );
  }

  /**
   * Create Jira tickets for your findings. You can create tickets by passing in a list of issue_ids or
   * by passing in filter query parameters to dynamically select findings. If passing in filters, Semgrep
   * will skip already ticketed findings. This endpoint is synchronous, so it may take some time for your
   * request to resolve. Unlike creating tickets in-app, if ticket creation fails we won't automatically
   * retry. This endpoint accepts a limit parameter (defaulting to 20) to limit the number of tickets
   * created per request. If you specify a list of issue_ids greater than this limit, or your selected
   * filters match on a number of issues greater than this limit, issues that were not ticketed are
   * included in the Failed part of the response object. You can send another request to create tickets
   * for these skipped issues. By default, findings belonging to the same repository and the same rule
   * will be grouped together into a single Jira ticket. You can override this using the group_issues
   * query parameter. Up to 50 issues can be grouped into a single ticket. You can optionally override
   * the Jira project you create tickets in by passing in a Jira project ID as jira_project_id (the
   * numeric ID rather than the project key). You can fetch this ID using the Jira API.
   *
   * @param deploymentSlug
   * @param body
   * @return Response from the API call
   */
  async createTicket(
    deploymentSlug: string,
    body: CreateTicketRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ProtosOpenapiV1CreateTicketResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      deploymentSlug: [deploymentSlug, string()],
      body: [body, createTicketRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentSlug}/tickets`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(
      protosOpenapiV1CreateTicketResponseSchema,
      requestOptions
    );
  }
}
