/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  BulkTriageRequest,
  bulkTriageRequestSchema,
} from '../models/bulkTriageRequest.js';
import {
  BulkTriageResponse,
  bulkTriageResponseSchema,
} from '../models/bulkTriageResponse.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';

export class TriageServiceApi extends BaseApi {
  /**
   * Bulk triage your findings. You can select the findings to triage by passing in a list of finding IDs
   * as issue_ids, or by passing in filter query parameters. You must specify the issue_type of the
   * findings you want to bulk triage. One of new_triage_state or new_note is required. If specifying a
   * new_triage_reason, you must also use new_triage_state=ignored. Some filters only apply for findings
   * associated with a given product.
   *
   * @param deploymentSlug
   * @param body
   * @return Response from the API call
   */
  async triageServiceBulkTriage(
    deploymentSlug: string,
    body: BulkTriageRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<BulkTriageResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      deploymentSlug: [deploymentSlug, string()],
      body: [body, bulkTriageRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/api/v1/deployments/${mapped.deploymentSlug}/triage`;
    req.authenticate([{ semgrepWebToken: true }]);
    return req.callAsJson(bulkTriageResponseSchema, requestOptions);
  }
}
