/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface AddProjectTagsRequest {
  /** Slug of the deployment name. Can be found at `/deployments`, or in your Settings in the web UI. */
  deploymentSlug: string;
  /** Name of the project, typically the repository formatted as a path. */
  projectName: string;
  tags?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const addProjectTagsRequestSchema: Schema<AddProjectTagsRequest> = typedExpandoObject(
  {
    deploymentSlug: ['deploymentSlug', string()],
    projectName: ['projectName', string()],
    tags: ['tags', optional(array(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
