/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Assistant, assistantSchema } from './assistant.js';
import {
  ClickToFixFailure,
  clickToFixFailureSchema,
} from './clickToFixFailure.js';
import { ClickToFixPr, clickToFixPrSchema } from './clickToFixPr.js';
import { Confidence1, confidence1Schema } from './confidence1.js';
import { ExternalTicket, externalTicketSchema } from './externalTicket.js';
import { FindingLocation, findingLocationSchema } from './findingLocation.js';
import {
  FindingRepository,
  findingRepositorySchema,
} from './findingRepository.js';
import { FindingRule, findingRuleSchema } from './findingRule.js';
import { PolicyReference, policyReferenceSchema } from './policyReference.js';
import { ReviewComment, reviewCommentSchema } from './reviewComment.js';
import { Severity1, severity1Schema } from './severity1.js';
import { State, stateSchema } from './state.js';
import { Status, statusSchema } from './status.js';
import { TriageReason, triageReasonSchema } from './triageReason.js';
import { TriageState, triageStateSchema } from './triageState.js';

/** An AI-powered scan finding that Semgrep has identified in your organization */
export interface AiPoweredScanFinding {
  /** AI-generated description of the potential impact if this vulnerability is exploited */
  aiImpact?: string;
  /** Semgrep Assistant data. Only present if Assistant is enabled */
  assistant?: Assistant;
  /** Failed PR creation attempts by Semgrep's autofix feature (Click to Fix) for this finding */
  clickToFixFailures?: ClickToFixFailure[];
  /** Pull requests created by Semgrep's autofix feature (Click to Fix) for this finding */
  clickToFixPrs?: ClickToFixPr[];
  /** Confidence of the finding, derived from the rule that triggered it */
  confidence?: Confidence1;
  /** The timestamp when this finding was created */
  createdAt?: string;
  /** External ticket associated with finding */
  externalTicket?: ExternalTicket;
  /** Unique ID of the Semgrep scan that first identified this finding */
  firstSeenScanId?: bigint;
  /** Unique ID of this finding */
  id?: bigint;
  /** The source URL including file and line number */
  lineOfCodeUrl?: string;
  /** Location of the record in a file, as reported by Semgrep. If null, then the information does not exist or lacks integrity (older or broken scans) */
  location?: FindingLocation;
  /** ID calculated based on a finding's file path, rule identifier and pattern, and index */
  matchBasedId?: string;
  /** External reference to the source of this finding (e.g. PR) */
  ref?: string;
  /** The timestamp when this finding was detected by Semgrep (the first time, or when reintroduced) */
  relevantSince?: string;
  /** Which repository this finding was identified in */
  repository?: FindingRepository;
  /** List of external review comment information associated with a finding */
  reviewComments?: ReviewComment[];
  /** Rule that applies to this finding */
  rule?: FindingRule;
  /** Deprecated in favor of rule.message. Rule message at the time of finding identification. Older findings may not have a value for this field */
  ruleMessage?: string;
  /** Deprecated in favor of rule.name */
  ruleName?: string;
  /** Severity of the finding, derived from the rule that triggered it. Low is equivalent to INFO, Medium to WARNING, and High to ERROR */
  severity?: Severity1;
  /** Reference to a policy, with some basic information. If null, then the information does not exist or lacks integrity (older or broken scans) */
  sourcingPolicy?: PolicyReference;
  /** The finding's resolution state. Managed only by changes detected at scan time, the `state` is combined with `triage_state` to ultimately determine a final `status` which is exposed in the UI and API */
  state?: State;
  /** When this issue's `state` (resolution state) was last updated, as distinct from when the issue was triaged (`triaged_at`) */
  stateUpdatedAt?: string;
  /** The finding's status as exposed in the UI. Status is a derived property combining information from the finding `state` and `triage_state`. The `triage_state` can be used to override the scan state if the finding is still detected */
  status?: Status;
  /** ID calculated based on a finding's file path, rule identifier and matched code, and index. Prefer `match_based_id` */
  syntacticId?: string;
  /** The detailed comment provided during triage */
  triageComment?: string;
  /** Reason provided when this issue was triaged */
  triageReason?: TriageReason;
  /** The finding's triage state. Note: "reviewing" and "fixing" are only in private beta. Set by the user and used along with state to generate the final "status" viewable in the UI */
  triageState?: TriageState;
  /** When the finding was triaged */
  triagedAt?: string;
  additionalProperties?: Record<string, unknown>;
}

export const aiPoweredScanFindingSchema: Schema<AiPoweredScanFinding> = lazy(
  () =>
    typedExpandoObject(
      {
        aiImpact: ['ai_impact', optional(string())],
        assistant: ['assistant', optional(assistantSchema)],
        clickToFixFailures: [
          'click_to_fix_failures',
          optional(array(clickToFixFailureSchema)),
        ],
        clickToFixPrs: [
          'click_to_fix_prs',
          optional(array(clickToFixPrSchema)),
        ],
        confidence: ['confidence', optional(confidence1Schema)],
        createdAt: ['created_at', optional(string())],
        externalTicket: ['external_ticket', optional(externalTicketSchema)],
        firstSeenScanId: ['first_seen_scan_id', optional(bigint())],
        id: ['id', optional(bigint())],
        lineOfCodeUrl: ['line_of_code_url', optional(string())],
        location: ['location', optional(findingLocationSchema)],
        matchBasedId: ['match_based_id', optional(string())],
        ref: ['ref', optional(string())],
        relevantSince: ['relevant_since', optional(string())],
        repository: ['repository', optional(findingRepositorySchema)],
        reviewComments: [
          'review_comments',
          optional(array(reviewCommentSchema)),
        ],
        rule: ['rule', optional(findingRuleSchema)],
        ruleMessage: ['rule_message', optional(string())],
        ruleName: ['rule_name', optional(string())],
        severity: ['severity', optional(severity1Schema)],
        sourcingPolicy: ['sourcing_policy', optional(policyReferenceSchema)],
        state: ['state', optional(stateSchema)],
        stateUpdatedAt: ['state_updated_at', optional(string())],
        status: ['status', optional(statusSchema)],
        syntacticId: ['syntactic_id', optional(string())],
        triageComment: ['triage_comment', optional(string())],
        triageReason: ['triage_reason', optional(triageReasonSchema)],
        triageState: ['triage_state', optional(triageStateSchema)],
        triagedAt: ['triaged_at', optional(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
