/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AiPoweredScanFinding,
  aiPoweredScanFindingSchema,
} from './aiPoweredScanFinding.js';

/** A list of AI-powered scan findings that Semgrep has identified in your organization */
export interface AiSastFindings {
  /** A list of AI-powered scan findings. */
  findings?: AiPoweredScanFinding[];
  additionalProperties?: Record<string, unknown>;
}

export const aiSastFindingsSchema: Schema<AiSastFindings> = lazy(() =>
  typedExpandoObject(
    { findings: ['findings', optional(array(aiPoweredScanFindingSchema))] },
    'additionalProperties',
    optional(unknown())
  )
);
