/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ApiV1DeploymentsFindingsResponseFindings,
  apiV1DeploymentsFindingsResponseFindingsSchema,
} from './containers/apiV1DeploymentsFindingsResponseFindings.js';

export interface ApiV1DeploymentsFindingsResponse {
  findings?: ApiV1DeploymentsFindingsResponseFindings[];
  additionalProperties?: Record<string, unknown>;
}

export const apiV1DeploymentsFindingsResponseSchema: Schema<ApiV1DeploymentsFindingsResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        findings: [
          'findings',
          optional(array(apiV1DeploymentsFindingsResponseFindingsSchema)),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
