/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Autofix, autofixSchema } from './autofix.js';
import { Autotriage, autotriageSchema } from './autotriage.js';
import { Component, componentSchema } from './component.js';
import { Guidance, guidanceSchema } from './guidance.js';
import { RuleExplanation, ruleExplanationSchema } from './ruleExplanation.js';

/** Semgrep Assistant data. Only present if Assistant is enabled */
export interface Assistant {
  /** Fix data generated by Semgrep Assistant */
  autofix?: Autofix;
  /** Triage recommendation generated by Semgrep Assistant */
  autotriage?: Autotriage;
  /** Semgrep Assistant's guess as for what the matched source code's purpose is */
  component?: Component;
  /** Remediation guidance generated by Semgrep Assistant */
  guidance?: Guidance;
  /** AI-generated explanation of why a rule flagged this specific code */
  ruleExplanation?: RuleExplanation;
  additionalProperties?: Record<string, unknown>;
}

export const assistantSchema: Schema<Assistant> = lazy(() =>
  typedExpandoObject(
    {
      autofix: ['autofix', optional(autofixSchema)],
      autotriage: ['autotriage', optional(autotriageSchema)],
      component: ['component', optional(componentSchema)],
      guidance: ['guidance', optional(guidanceSchema)],
      ruleExplanation: ['rule_explanation', optional(ruleExplanationSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
