/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Fix data generated by Semgrep Assistant */
export interface Autofix {
  /** DEPRECATED: This field is deprecated and will always be an empty string. Find a description of how this fix works under `assistant.guidance` */
  explanation?: string;
  /** Source code that replaces all matched lines to fix this finding. AI generated content, review carefully */
  fixCode?: string;
  additionalProperties?: Record<string, unknown>;
}

export const autofixSchema: Schema<Autofix> = typedExpandoObject(
  {
    explanation: ['explanation', optional(string())],
    fixCode: ['fix_code', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
