/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Verdict1, verdict1Schema } from './verdict1.js';

/** Triage recommendation generated by Semgrep Assistant */
export interface Autotriage {
  /** The reasoning for a `false_positive` verdict; this explains why you might want to ignore the finding. Empty string if verdict is `true_positive` */
  reason?: string;
  /** The verdict is `true_positive` if Assistant recommends fixing, `false_positive` if Assistant recommends ignoring this finding. AI generated decision, review carefully */
  verdict?: Verdict1;
  additionalProperties?: Record<string, unknown>;
}

export const autotriageSchema: Schema<Autotriage> = typedExpandoObject(
  {
    reason: ['reason', optional(string())],
    verdict: ['verdict', optional(verdict1Schema)],
  },
  'additionalProperties',
  optional(unknown())
);
