/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AutotriageVerdict
 */
export enum AutotriageVerdict {
  TruePositive = 'true_positive',
  FalsePositive = 'false_positive',
}

/**
 * Schema for AutotriageVerdict
 */
export const autotriageVerdictSchema: Schema<AutotriageVerdict> = stringEnum(
  AutotriageVerdict
);
