/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AutotriageVerdict2
 */
export enum AutotriageVerdict2 {
  TruePositive = 'true_positive',
  FalsePositive = 'false_positive',
}

/**
 * Schema for AutotriageVerdict2
 */
export const autotriageVerdict2Schema: Schema<AutotriageVerdict2> = stringEnum(
  AutotriageVerdict2
);
