/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BulkTriageResponse {
  /** Number of items updated */
  numTriaged: bigint;
  /** List of triaged issue IDs */
  triagedIssues: bigint[];
  additionalProperties?: Record<string, unknown>;
}

export const bulkTriageResponseSchema: Schema<BulkTriageResponse> = typedExpandoObject(
  {
    numTriaged: ['num_triaged', bigint()],
    triagedIssues: ['triaged_issues', array(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
