/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AutotriageVerdict,
  autotriageVerdictSchema,
} from './autotriageVerdict.js';
import { Confidence3, confidence3Schema } from './confidence3.js';
import { EpssProbability, epssProbabilitySchema } from './epssProbability.js';
import { Exposures, exposuresSchema } from './exposures.js';
import { IssueType, issueTypeSchema } from './issueType.js';
import { NewTriageReason, newTriageReasonSchema } from './newTriageReason.js';
import { NewTriageState, newTriageStateSchema } from './newTriageState.js';
import { PolicyMode1, policyMode1Schema } from './policyMode1.js';
import {
  RepositoryVisibility,
  repositoryVisibilitySchema,
} from './repositoryVisibility.js';
import { Severities, severitiesSchema } from './severities.js';
import { Status1, status1Schema } from './status1.js';
import { Transitivities, transitivitiesSchema } from './transitivities.js';
import { TriageReasons, triageReasonsSchema } from './triageReasons.js';
import { ValidationState, validationStateSchema } from './validationState.js';

export interface BulkTriageRequest {
  /** The autotriage verdict to filter by */
  autotriageVerdict?: AutotriageVerdict;
  /** List of categories to filter by */
  categories?: string[];
  /** List of component tags to filter by */
  componentTags?: string[];
  /** List of confidence levels to filter by */
  confidence?: Confidence3;
  /** Filter by dependency name. Only applies for sca findings. */
  dependencies?: string[];
  /** Filter by EPSS probability (likelihood of exploit). Only applies for sca findings. */
  epssProbability?: EpssProbability;
  /** Filter by exposure (reachability type). Only applies for sca findings. Reachability is the ability of an attacker to access a vulnerability in a system. */
  exposures?: Exposures;
  /** Whether to include historical findings. Only applies for secrets findings. Defaults to true. */
  includeHistorical?: boolean;
  /** An array of issue IDs to act on. If this is not provided, an issue filter should be provided. */
  issueIds?: bigint[];
  /** Type of findings to bulk triage. */
  issueType: IssueType;
  /** Max number of issues to triage. Must be an integer between 1 and 3000. Defaults to 3000. When selecting findings to triage, Semgrep will also triage findings with the same fingerprint on other branches. As a result, the list of triaged issue_ids returned in the response may be higher than the specified limit. */
  limit?: bigint;
  /** The note to attach to the bulk triaged findings. Maximum 3000 characters. */
  newNote?: string;
  /** The reason for triaging to a given triage state. */
  newTriageReason?: NewTriageReason;
  /** The triage state you would like to bulk triage your findings to. */
  newTriageState?: NewTriageState;
  /** List of policy modes to filter by */
  policies?: string[];
  /** List of policy modes to filter by */
  policyMode?: PolicyMode1;
  /** Filter by whether a finding is only available with Semgrep Pro features. */
  proOnly?: boolean;
  /** List of project tags to filter by */
  projectTags?: string[];
  /** Branch reference to filter by */
  ref?: string;
  /** List of repository names to filter by */
  repos?: string[];
  /** Filter by repository visibility. Only applies for secrets findings. */
  repositoryVisibility?: RepositoryVisibility;
  /** List of rule names to filter by */
  rules?: string[];
  /** List of Semgrep Registry rulesets to filter by */
  ruleset?: string[];
  /** Filter by type of secret (typically provider-related). Only applies for secrets findings. */
  secretTypes?: string[];
  /** List of severities to filter by */
  severities?: Severities;
  /** Epoch timestamp in seconds. Filters using the relevant_since field: the timestamp when this finding was detected by Semgrep (the first time, or when reintroduced). */
  since?: string;
  /** The status to filter by */
  status?: Status1;
  /** Filter by transitivity of a dependency. Only applies for sca findings. */
  transitivities?: Transitivities;
  /** List of triage reasons to filter by */
  triageReasons?: TriageReasons;
  /** Filter by whether a secret could be validated. Only applies for secrets findings. */
  validationState?: ValidationState;
  additionalProperties?: Record<string, unknown>;
}

export const bulkTriageRequestSchema: Schema<BulkTriageRequest> = typedExpandoObject(
  {
    autotriageVerdict: [
      'autotriage_verdict',
      optional(autotriageVerdictSchema),
    ],
    categories: ['categories', optional(array(string()))],
    componentTags: ['component_tags', optional(array(string()))],
    confidence: ['confidence', optional(confidence3Schema)],
    dependencies: ['dependencies', optional(array(string()))],
    epssProbability: ['epss_probability', optional(epssProbabilitySchema)],
    exposures: ['exposures', optional(exposuresSchema)],
    includeHistorical: ['include_historical', optional(boolean())],
    issueIds: ['issue_ids', optional(array(bigint()))],
    issueType: ['issue_type', issueTypeSchema],
    limit: ['limit', optional(bigint())],
    newNote: ['new_note', optional(string())],
    newTriageReason: ['new_triage_reason', optional(newTriageReasonSchema)],
    newTriageState: ['new_triage_state', optional(newTriageStateSchema)],
    policies: ['policies', optional(array(string()))],
    policyMode: ['policy_mode', optional(policyMode1Schema)],
    proOnly: ['pro_only', optional(boolean())],
    projectTags: ['project_tags', optional(array(string()))],
    ref: ['ref', optional(string())],
    repos: ['repos', optional(array(string()))],
    repositoryVisibility: [
      'repository_visibility',
      optional(repositoryVisibilitySchema),
    ],
    rules: ['rules', optional(array(string()))],
    ruleset: ['ruleset', optional(array(string()))],
    secretTypes: ['secret_types', optional(array(string()))],
    severities: ['severities', optional(severitiesSchema)],
    since: ['since', optional(string())],
    status: ['status', optional(status1Schema)],
    transitivities: ['transitivities', optional(transitivitiesSchema)],
    triageReasons: ['triage_reasons', optional(triageReasonsSchema)],
    validationState: ['validation_state', optional(validationStateSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
