/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** A pull request created by Semgrep's Click to Fix feature */
export interface ClickToFixPr {
  /** When this PR was created */
  createdAt?: string;
  /** URL of the pull request */
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const clickToFixPrSchema: Schema<ClickToFixPr> = typedExpandoObject(
  {
    createdAt: ['created_at', optional(string())],
    url: ['url', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
