/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** A failed PR creation attempt by Semgrep's Click to Fix feature */
export interface ClickToFixFailure {
  /** When this failure occurred */
  createdAt?: string;
  /** Reason for the PR creation failure */
  reason?: string;
  additionalProperties?: Record<string, unknown>;
}

export const clickToFixFailureSchema: Schema<ClickToFixFailure> = typedExpandoObject(
  {
    createdAt: ['created_at', optional(string())],
    reason: ['reason', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
