/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ClickToFixPrState
 */
export enum ClickToFixPrState {
  Open = 'open',
  Merged = 'merged',
}

/**
 * Schema for ClickToFixPrState
 */
export const clickToFixPrStateSchema: Schema<ClickToFixPrState> = stringEnum(
  ClickToFixPrState
);
