/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Risk, riskSchema } from './risk.js';

/** Semgrep Assistant's guess as for what the matched source code's purpose is */
export interface Component {
  /** Component risk level */
  risk?: Risk;
  /** Component tag */
  tag?: string;
  additionalProperties?: Record<string, unknown>;
}

export const componentSchema: Schema<Component> = typedExpandoObject(
  { risk: ['risk', optional(riskSchema)], tag: ['tag', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
