/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Confidence1
 */
export enum Confidence1 {
  Low = 'low',
  Medium = 'medium',
  High = 'high',
}

/**
 * Schema for Confidence1
 */
export const confidence1Schema: Schema<Confidence1> = stringEnum(Confidence1);
