/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Confidence8
 */
export enum Confidence8 {
  Low = 'low',
  Medium = 'medium',
  High = 'high',
}

/**
 * Schema for Confidence8
 */
export const confidence8Schema: Schema<Confidence8> = stringEnum(Confidence8);
