/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Confidence7
 */
export enum Confidence7 {
  ConfidenceHigh = 'CONFIDENCE_HIGH',
  ConfidenceMedium = 'CONFIDENCE_MEDIUM',
  ConfidenceLow = 'CONFIDENCE_LOW',
}

/**
 * Schema for Confidence7
 */
export const confidence7Schema: Schema<Confidence7> = stringEnum(Confidence7);
