/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Confidence3
 */
export enum Confidence3 {
  Low = 'low',
  Medium = 'medium',
  High = 'high',
}

/**
 * Schema for Confidence3
 */
export const confidence3Schema: Schema<Confidence3> = stringEnum(Confidence3);
