/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Confidence2
 */
export enum Confidence2 {
  Low = 'low',
  Medium = 'medium',
  High = 'high',
}

/**
 * Schema for Confidence2
 */
export const confidence2Schema: Schema<Confidence2> = stringEnum(Confidence2);
