/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Confidence
 */
export enum Confidence {
  ConfidenceHigh = 'CONFIDENCE_HIGH',
  ConfidenceMedium = 'CONFIDENCE_MEDIUM',
  ConfidenceLow = 'CONFIDENCE_LOW',
}

/**
 * Schema for Confidence
 */
export const confidenceSchema: Schema<Confidence> = stringEnum(Confidence);
