/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  MetadataComponentType,
  metadataComponentTypeSchema,
} from './metadataComponentType.js';
import {
  ProtosScaV1SbomFormatVersion,
  protosScaV1SbomFormatVersionSchema,
} from './protosScaV1SbomFormatVersion.js';
import {
  ProtosScaV1SbomMetadataSupplier,
  protosScaV1SbomMetadataSupplierSchema,
} from './protosScaV1SbomMetadataSupplier.js';
import {
  SbomOutputFormat,
  sbomOutputFormatSchema,
} from './sbomOutputFormat.js';

export interface CreateSbomExportRequest {
  /** Deployment ID (numeric). Example: `123`. Can be found at `/deployments`, or in your Settings in the web UI. */
  deploymentId: string;
  formatVersion?: ProtosScaV1SbomFormatVersion;
  /**
   * Metadata component type for the SBOM export.
   * | value | description |
   * |-------|---------------|
   * | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_APPLICATION |  |
   * | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_FRAMEWORK |  |
   * | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_LIBRARY |  |
   * | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_CONTAINER |  |
   * | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_PLATFORM |  |
   * | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_OPERATING_SYSTEM |  |
   * | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_DEVICE |  |
   * | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_DEVICE_DRIVER |  |
   * | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_FIRMWARE |  |
   * | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_FILE |  |
   * | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_MACHINE_LEARNING_MODEL |  |
   * | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_DATA |  |
   */
  metadataComponentType?: MetadataComponentType;
  metadataSupplier?: ProtosScaV1SbomMetadataSupplier;
  /** Branch to export SBOM for (Ex. ref=`refs/pull/1234/merge`). */
  ref?: string;
  /** Repository ID to export SBOM for. */
  repositoryId?: string;
  /**
   * SBOM output format for the SBOM export.
   * | value | description |
   * |-------|---------------|
   * | SBOM_OUTPUT_FORMAT_JSON |  |
   */
  sbomOutputFormat?: SbomOutputFormat;
  additionalProperties?: Record<string, unknown>;
}

export const createSbomExportRequestSchema: Schema<CreateSbomExportRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        deploymentId: ['deploymentId', string()],
        formatVersion: [
          'formatVersion',
          optional(protosScaV1SbomFormatVersionSchema),
        ],
        metadataComponentType: [
          'metadataComponentType',
          optional(metadataComponentTypeSchema),
        ],
        metadataSupplier: [
          'metadataSupplier',
          optional(protosScaV1SbomMetadataSupplierSchema),
        ],
        ref: ['ref', optional(string())],
        repositoryId: ['repositoryId', optional(string())],
        sbomOutputFormat: [
          'sbomOutputFormat',
          optional(sbomOutputFormatSchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
