/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AutotriageVerdict,
  autotriageVerdictSchema,
} from './autotriageVerdict.js';
import { Confidence3, confidence3Schema } from './confidence3.js';
import { EpssProbability, epssProbabilitySchema } from './epssProbability.js';
import { Exposures, exposuresSchema } from './exposures.js';
import { IssueType1, issueType1Schema } from './issueType1.js';
import { PolicyMode1, policyMode1Schema } from './policyMode1.js';
import {
  RepositoryVisibility,
  repositoryVisibilitySchema,
} from './repositoryVisibility.js';
import { Severities, severitiesSchema } from './severities.js';
import { Status1, status1Schema } from './status1.js';
import { Transitivities, transitivitiesSchema } from './transitivities.js';
import { TriageReasons, triageReasonsSchema } from './triageReasons.js';
import { ValidationState, validationStateSchema } from './validationState.js';

/** Create ticket request */
export interface CreateTicketRequest {
  /** The autotriage verdict to filter by */
  autotriageVerdict?: AutotriageVerdict;
  /** List of categories to filter by */
  categories?: string[];
  /** List of component tags to filter by */
  componentTags?: string[];
  /** List of confidence levels to filter by */
  confidence?: Confidence3;
  /** Filter by dependency name. Only applies for sca findings. */
  dependencies?: string[];
  /** Deployment slug. Can be found at `/deployments`, or in your Settings in the web UI. */
  deploymentSlug: string;
  /** Filter by EPSS probability (likelihood of exploit). Only applies for sca findings. */
  epssProbability?: EpssProbability;
  /** Filter by exposure (reachability type). Only applies for sca findings. Reachability is the ability of an attacker to access a vulnerability in a system. */
  exposures?: Exposures;
  /** Whether or not to group findings from the same rule and repository into a single ticket. Defaults to true. */
  groupIssues?: boolean;
  /** Whether to include historical findings. Only applies for secrets findings. Defaults to true. */
  includeHistorical?: boolean;
  /** An array of issue IDs to act on. If this is not provided, an issue filter should be provided. */
  issueIds?: string[];
  /** Type of findings to create tickets for. */
  issueType: IssueType1;
  /** Optional numeric Jira project ID to associate with the created tickets. If not specified, defaults to the project configured in your integration settings. You can fetch this ID using the Jira API. */
  jiraProjectId?: string;
  /** Max number of tickets to create. Must be an integer between 1 and 20. Defaults to 20 */
  limit?: bigint;
  /** List of policy modes to filter by */
  policies?: string[];
  /** List of policy modes to filter by */
  policyMode?: PolicyMode1;
  /** Filter by whether a finding is only available with Semgrep Pro features. Only applies for sast findings. */
  proOnly?: boolean;
  /** List of project tags to filter by */
  projectTags?: string[];
  /** Branch reference to filter by */
  ref?: string;
  /** List of repository names to filter by */
  repos?: string[];
  /** Filter by repository visibility. Only applies for secrets findings. */
  repositoryVisibility?: RepositoryVisibility;
  /** List of rule names to filter by */
  rules?: string[];
  /** List of Semgrep Registry rulesets to filter by */
  ruleset?: string[];
  /** Filter by type of secret (typically provider-related). Only applies for secrets findings. */
  secretTypes?: string[];
  /** List of severities to filter by */
  severities?: Severities;
  /** Epoch timestamp in seconds. Filters using the relevant_since field: the timestamp when this finding was detected by Semgrep (the first time, or when reintroduced). */
  since?: string;
  /** The status to filter by */
  status?: Status1;
  /** Filter by transitivity of a dependency. Only applies for sca findings. */
  transitivities?: Transitivities;
  /** List of triage reasons to filter by */
  triageReasons?: TriageReasons;
  /** Filter by whether a secret could be validated. Only applies for secrets findings. */
  validationState?: ValidationState;
  additionalProperties?: Record<string, unknown>;
}

export const createTicketRequestSchema: Schema<CreateTicketRequest> = typedExpandoObject(
  {
    autotriageVerdict: [
      'autotriage_verdict',
      optional(autotriageVerdictSchema),
    ],
    categories: ['categories', optional(array(string()))],
    componentTags: ['component_tags', optional(array(string()))],
    confidence: ['confidence', optional(confidence3Schema)],
    dependencies: ['dependencies', optional(array(string()))],
    deploymentSlug: ['deploymentSlug', string()],
    epssProbability: ['epss_probability', optional(epssProbabilitySchema)],
    exposures: ['exposures', optional(exposuresSchema)],
    groupIssues: ['group_issues', optional(boolean())],
    includeHistorical: ['include_historical', optional(boolean())],
    issueIds: ['issue_ids', optional(array(string()))],
    issueType: ['issue_type', issueType1Schema],
    jiraProjectId: ['jira_project_id', optional(string())],
    limit: ['limit', optional(bigint())],
    policies: ['policies', optional(array(string()))],
    policyMode: ['policy_mode', optional(policyMode1Schema)],
    proOnly: ['pro_only', optional(boolean())],
    projectTags: ['project_tags', optional(array(string()))],
    ref: ['ref', optional(string())],
    repos: ['repos', optional(array(string()))],
    repositoryVisibility: [
      'repository_visibility',
      optional(repositoryVisibilitySchema),
    ],
    rules: ['rules', optional(array(string()))],
    ruleset: ['ruleset', optional(array(string()))],
    secretTypes: ['secret_types', optional(array(string()))],
    severities: ['severities', optional(severitiesSchema)],
    since: ['since', optional(string())],
    status: ['status', optional(status1Schema)],
    transitivities: ['transitivities', optional(transitivitiesSchema)],
    triageReasons: ['triage_reasons', optional(triageReasonsSchema)],
    validationState: ['validation_state', optional(validationStateSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
