/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface CreateSbomExportResponse {
  /** Task token for the SBOM export job. */
  taskToken: string;
  additionalProperties?: Record<string, unknown>;
}

export const createSbomExportResponseSchema: Schema<CreateSbomExportResponse> = typedExpandoObject(
  { taskToken: ['taskToken', string()] },
  'additionalProperties',
  optional(unknown())
);
