/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for CyclonedxVersion
 */
export enum CyclonedxVersion {
  SbomCycloneDxVersionV14 = 'SBOM_CYCLONE_DX_VERSION_V1_4',
  SbomCycloneDxVersionV15 = 'SBOM_CYCLONE_DX_VERSION_V1_5',
  SbomCycloneDxVersionV16 = 'SBOM_CYCLONE_DX_VERSION_V1_6',
  SbomCycloneDxVersionV17 = 'SBOM_CYCLONE_DX_VERSION_V1_7',
}

/**
 * Schema for CyclonedxVersion
 */
export const cyclonedxVersionSchema: Schema<CyclonedxVersion> = stringEnum(
  CyclonedxVersion
);
