/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Successfully deleted the project. */
export interface DeleteProjectResponse {
  /** The name of the deleted project. */
  projectName: string;
  additionalProperties?: Record<string, unknown>;
}

export const deleteProjectResponseSchema: Schema<DeleteProjectResponse> = typedExpandoObject(
  { projectName: ['project_name', string()] },
  'additionalProperties',
  optional(unknown())
);
