/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Project, projectSchema } from './project.js';

/** Successfully removed tags from project. */
export interface DeleteProjectTagsResponse {
  /** A project in your organization that uses Semgrep. */
  project: Project;
  additionalProperties?: Record<string, unknown>;
}

export const deleteProjectTagsResponseSchema: Schema<DeleteProjectTagsResponse> = lazy(
  () =>
    typedExpandoObject(
      { project: ['project', projectSchema] },
      'additionalProperties',
      optional(unknown())
    )
);
