/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  EndpointReference,
  endpointReferenceSchema,
} from './endpointReference.js';

/** Deployment record, with relevant meta-data and further accesses. */
export interface Deployment {
  findings?: EndpointReference;
  /** Unique numerical identifier of the deployment. */
  id: bigint;
  /** Human readable name. */
  name: string;
  /** Sanitized machine-readable name. Used as primary identifier through the web API. */
  slug: string;
  additionalProperties?: Record<string, unknown>;
}

export const deploymentSchema: Schema<Deployment> = lazy(() =>
  typedExpandoObject(
    {
      findings: ['findings', optional(endpointReferenceSchema)],
      id: ['id', bigint()],
      name: ['name', string()],
      slug: ['slug', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
