/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Ecosystem2
 */
export enum Ecosystem2 {
  NoPackageManager = 'no_package_manager',
  Npm = 'npm',
  Pypi = 'pypi',
  Gomod = 'gomod',
  Cargo = 'cargo',
  Maven = 'maven',
  Gem = 'gem',
  Composer = 'composer',
  Nuget = 'nuget',
  Pub = 'pub',
  Swiftpm = 'swiftpm',
  Hex = 'hex',
}

/**
 * Schema for Ecosystem2
 */
export const ecosystem2Schema: Schema<Ecosystem2> = stringEnum(Ecosystem2);
