/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Ecosystem
 */
export enum Ecosystem {
  NoPackageManager = 'no_package_manager',
  Npm = 'npm',
  Pypi = 'pypi',
  Gomod = 'gomod',
  Cargo = 'cargo',
  Maven = 'maven',
  Gem = 'gem',
  Composer = 'composer',
  Nuget = 'nuget',
  Pub = 'pub',
  Swiftpm = 'swiftpm',
  Hex = 'hex',
  Cocoapods = 'cocoapods',
  Mix = 'mix',
  Opam = 'opam',
}

/**
 * Schema for Ecosystem
 */
export const ecosystemSchema: Schema<Ecosystem> = stringEnum(Ecosystem);
