/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface EndpointReference {
  /** URL that the reference is pointing to. */
  url: string;
  additionalProperties?: Record<string, unknown>;
}

export const endpointReferenceSchema: Schema<EndpointReference> = typedExpandoObject(
  { url: ['url', string()] },
  'additionalProperties',
  optional(unknown())
);
