/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for EpssProbability
 */
export enum EpssProbability {
  Low = 'low',
  Medium = 'medium',
  High = 'high',
  None = 'none',
}

/**
 * Schema for EpssProbability
 */
export const epssProbabilitySchema: Schema<EpssProbability> = stringEnum(
  EpssProbability
);
