/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** The score assigned by FIRST.org's Exploitation Probability Scoring System */
export interface EpssScore {
  /** This EPSS score's percentile among all EPSS scores, from 0 to 1 */
  percentile?: number;
  /** The explotation probability, from 0 to 1 */
  score?: number;
  additionalProperties?: Record<string, unknown>;
}

export const epssScoreSchema: Schema<EpssScore> = typedExpandoObject(
  {
    percentile: ['percentile', optional(number())],
    score: ['score', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
