/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Exposures2
 */
export enum Exposures2 {
  Reachable = 'reachable',
  AlwaysReachable = 'always_reachable',
  ConditionallyReachable = 'conditionally_reachable',
  Unreachable = 'unreachable',
  Unknown = 'unknown',
}

/**
 * Schema for Exposures2
 */
export const exposures2Schema: Schema<Exposures2> = stringEnum(Exposures2);
