/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Exposures
 */
export enum Exposures {
  Reachable = 'reachable',
  AlwaysReachable = 'always_reachable',
  ConditionallyReachable = 'conditionally_reachable',
  Unreachable = 'unreachable',
  Unknown = 'unknown',
}

/**
 * Schema for Exposures
 */
export const exposuresSchema: Schema<Exposures> = stringEnum(Exposures);
