/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** External ticket associated with finding */
export interface ExternalTicket {
  /** Identifier of the external ticket */
  externalSlug?: string;
  /** External ticket id */
  id?: bigint;
  /** Semgrep issue ids that are linked to this external ticket */
  linkedIssueIds?: bigint[];
  /** URL of the external ticket */
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const externalTicketSchema: Schema<ExternalTicket> = typedExpandoObject(
  {
    externalSlug: ['external_slug', optional(string())],
    id: ['id', optional(bigint())],
    linkedIssueIds: ['linked_issue_ids', optional(array(bigint()))],
    url: ['url', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
