/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Location of the record in a file, as reported by Semgrep. If null, then the information does not exist or lacks integrity (older or broken scans) */
export interface FindingLocation {
  /** Column at which the target starts */
  column?: bigint;
  /** Column at which the target ends */
  endColumn?: bigint;
  /** Line at which the target ends */
  endLine?: bigint;
  /** File path of the relevant line and column numbers */
  filePath?: string;
  /** Line at which the target starts */
  line?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const findingLocationSchema: Schema<FindingLocation> = typedExpandoObject(
  {
    column: ['column', optional(bigint())],
    endColumn: ['end_column', optional(bigint())],
    endLine: ['end_line', optional(bigint())],
    filePath: ['file_path', optional(string())],
    line: ['line', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
