/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Confidence2, confidence2Schema } from './confidence2.js';

/** Rule that applies to this finding */
export interface FindingRule {
  /** Category the rule is associated with */
  category?: string;
  /** Confidence level of the rule */
  confidence?: Confidence2;
  /** CWE names associated with the rule */
  cweNames?: string[];
  /** Rule message */
  message?: string;
  /** Name of the rule */
  name?: string;
  /** OWASP names associated with the rule */
  owaspNames?: string[];
  /** Subcategories of the rule */
  subcategories?: string[];
  /** Vulnerability classes the rule is associated with */
  vulnerabilityClasses?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const findingRuleSchema: Schema<FindingRule> = typedExpandoObject(
  {
    category: ['category', optional(string())],
    confidence: ['confidence', optional(confidence2Schema)],
    cweNames: ['cwe_names', optional(array(string()))],
    message: ['message', optional(string())],
    name: ['name', optional(string())],
    owaspNames: ['owasp_names', optional(array(string()))],
    subcategories: ['subcategories', optional(array(string()))],
    vulnerabilityClasses: ['vulnerability_classes', optional(array(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
