/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Which repository this finding was identified in */
export interface FindingRepository {
  /** The repository or named project that the finding is associated with */
  name?: string;
  /** The source URL from which this repository last scanned */
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const findingRepositorySchema: Schema<FindingRepository> = typedExpandoObject(
  { name: ['name', optional(string())], url: ['url', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
