/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Recommendation for fixing the vulnerability */
export interface FixRecommendation {
  /** The package for which a fix is recommended */
  mPackage?: string;
  /** The recommended version of the package */
  version?: string;
  additionalProperties?: Record<string, unknown>;
}

export const fixRecommendationSchema: Schema<FixRecommendation> = typedExpandoObject(
  {
    mPackage: ['package', optional(string())],
    version: ['version', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
