/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface FloatRange {
  /** End of the range */
  max?: number;
  /** Start of the range */
  min?: number;
  additionalProperties?: Record<string, unknown>;
}

export const floatRangeSchema: Schema<FloatRange> = typedExpandoObject(
  { max: ['max', optional(number())], min: ['min', optional(number())] },
  'additionalProperties',
  optional(unknown())
);
