/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Format
 */
export enum Format {
  SbomFormatCyclonedx = 'SBOM_FORMAT_CYCLONEDX',
}

/**
 * Schema for Format
 */
export const formatSchema: Schema<Format> = stringEnum(Format);
