/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Ecosystem2, ecosystem2Schema } from './ecosystem2.js';
import { Transitivity2, transitivity2Schema } from './transitivity2.js';

/** Information about the vulnerable package that was found in the codebase */
export interface FoundDependency {
  /** Ecosystem of the package */
  ecosystem?: Ecosystem2;
  /** URL to the specific line in the lockfile where the dependency is listed */
  lockfileLineUrl?: string;
  /** Name of the package that contains the vulnerability */
  mPackage?: string;
  /** Indicates whether the dependency is direct or transitive */
  transitivity?: Transitivity2;
  /** Version of the package that was found to be vulnerable */
  version?: string;
  additionalProperties?: Record<string, unknown>;
}

export const foundDependencySchema: Schema<FoundDependency> = typedExpandoObject(
  {
    ecosystem: ['ecosystem', optional(ecosystem2Schema)],
    lockfileLineUrl: ['lockfile_line_url', optional(string())],
    mPackage: ['package', optional(string())],
    transitivity: ['transitivity', optional(transitivity2Schema)],
    version: ['version', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
