/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Project, projectSchema } from './project.js';

/** Successfully retrieved details for the project. */
export interface GetProjectResponse {
  /** A project in your organization that uses Semgrep. */
  project: Project;
  additionalProperties?: Record<string, unknown>;
}

export const getProjectResponseSchema: Schema<GetProjectResponse> = lazy(() =>
  typedExpandoObject(
    { project: ['project', projectSchema] },
    'additionalProperties',
    optional(unknown())
  )
);
