/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Status3, status3Schema } from './status3.js';

export interface GetSbomExportResponse {
  /** URL to download the SBOM when status is COMPLETED. */
  downloadUrl?: string;
  /** Error message when status is FAILED. */
  errorMessage?: string;
  /**
   * Status of the SBOM export job.
   * | value | description |
   * |-------|---------------|
   * | SBOM_EXPORT_STATUS_IN_PROGRESS | The SBOM export job is in progress. |
   * | SBOM_EXPORT_STATUS_COMPLETED | The SBOM export job has completed. |
   * | SBOM_EXPORT_STATUS_FAILED | The SBOM export job has failed. |
   */
  status: Status3;
  additionalProperties?: Record<string, unknown>;
}

export const getSbomExportResponseSchema: Schema<GetSbomExportResponse> = typedExpandoObject(
  {
    downloadUrl: ['downloadUrl', optional(string())],
    errorMessage: ['errorMessage', optional(string())],
    status: ['status', status3Schema],
  },
  'additionalProperties',
  optional(unknown())
);
