/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Remediation guidance generated by Semgrep Assistant */
export interface Guidance {
  /** Step-by-step instructions explaining to a developer how to fix the finding. AI generated content, review carefully */
  instructions?: string;
  /** Short title explaining to a developer how to fix the finding. AI generated content, review carefully */
  summary?: string;
  additionalProperties?: Record<string, unknown>;
}

export const guidanceSchema: Schema<Guidance> = typedExpandoObject(
  {
    instructions: ['instructions', optional(string())],
    summary: ['summary', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
