/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for IssueType
 */
export enum IssueType {
  Sast = 'sast',
  Sca = 'sca',
  Secrets = 'secrets',
}

/**
 * Schema for IssueType
 */
export const issueTypeSchema: Schema<IssueType> = stringEnum(IssueType);
