/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for IssueType2
 */
export enum IssueType2 {
  Sast = 'sast',
  Sca = 'sca',
  AiSast = 'ai_sast',
}

/**
 * Schema for IssueType2
 */
export const issueType2Schema: Schema<IssueType2> = stringEnum(IssueType2);
