/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for IssueType1
 */
export enum IssueType1 {
  Sast = 'sast',
  Sca = 'sca',
  Secrets = 'secrets',
}

/**
 * Schema for IssueType1
 */
export const issueType1Schema: Schema<IssueType1> = stringEnum(IssueType1);
