/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for LicensePolicySettings
 */
export enum LicensePolicySettings {
  LicensePolicySettingAllow = 'LICENSE_POLICY_SETTING_ALLOW',
  LicensePolicySettingComment = 'LICENSE_POLICY_SETTING_COMMENT',
  LicensePolicySettingBlock = 'LICENSE_POLICY_SETTING_BLOCK',
}

/**
 * Schema for LicensePolicySettings
 */
export const licensePolicySettingsSchema: Schema<LicensePolicySettings> = stringEnum(
  LicensePolicySettings
);
