/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Link ticket request */
export interface LinkTicketRequest {
  /** Deployment ID. Can be found at /deployments, or in your Settings in the web UI. */
  deploymentId: string;
  /** An array of Semgrep finding IDs to link the ticket to. */
  issueIds: string[];
  /** The URL of the external ticket to link (e.g. https://myorg.atlassian.net/browse/SEC-123). */
  ticketUrl: string;
  additionalProperties?: Record<string, unknown>;
}

export const linkTicketRequestSchema: Schema<LinkTicketRequest> = typedExpandoObject(
  {
    deploymentId: ['deploymentId', string()],
    issueIds: ['issue_ids', array(string())],
    ticketUrl: ['ticket_url', string()],
  },
  'additionalProperties',
  optional(unknown())
);
