/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ProtosScaV1FoundDependency,
  protosScaV1FoundDependencySchema,
} from './protosScaV1FoundDependency.js';

export interface ListDependenciesResponse {
  /** Pass to next request to get next page of results. */
  cursor?: string;
  /** List of dependencies. */
  dependencies: ProtosScaV1FoundDependency[];
  /** True if there are more dependencies to get. */
  hasMore: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const listDependenciesResponseSchema: Schema<ListDependenciesResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        cursor: ['cursor', optional(string())],
        dependencies: ['dependencies', array(protosScaV1FoundDependencySchema)],
        hasMore: ['hasMore', boolean()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
