/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ProtosScaV1RepositoryDependencySummary,
  protosScaV1RepositoryDependencySummarySchema,
} from './protosScaV1RepositoryDependencySummary.js';

export interface ListRepositoriesForDependenciesResponse {
  /** Pass to next request to get next page of results. */
  cursor?: bigint;
  /** True if there are more repositories to get. */
  hasMore: boolean;
  /** List of repositories. */
  repositorySummaries: ProtosScaV1RepositoryDependencySummary[];
  additionalProperties?: Record<string, unknown>;
}

export const listRepositoriesForDependenciesResponseSchema: Schema<ListRepositoriesForDependenciesResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        cursor: ['cursor', optional(bigint())],
        hasMore: ['hasMore', boolean()],
        repositorySummaries: [
          'repositorySummaries',
          array(protosScaV1RepositoryDependencySummarySchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
