/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ListProject, listProjectSchema } from './listProject.js';

/** Return the list of projects in an organization. */
export interface ListProjectsResponse {
  projects: ListProject[];
  additionalProperties?: Record<string, unknown>;
}

export const listProjectsResponseSchema: Schema<ListProjectsResponse> = lazy(
  () =>
    typedExpandoObject(
      { projects: ['projects', array(listProjectSchema)] },
      'additionalProperties',
      optional(unknown())
    )
);
