/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ProtosScaV1LockfileDependencySummary,
  protosScaV1LockfileDependencySummarySchema,
} from './protosScaV1LockfileDependencySummary.js';

export interface ListLockfilesForDependenciesResponse {
  /** Pass to next request to get next page of results. */
  cursor?: string;
  /** True if there are more lockfiles to get. */
  hasMore: boolean;
  /** List of lockfiles. */
  lockfileSummaries: ProtosScaV1LockfileDependencySummary[];
  additionalProperties?: Record<string, unknown>;
}

export const listLockfilesForDependenciesResponseSchema: Schema<ListLockfilesForDependenciesResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        cursor: ['cursor', optional(string())],
        hasMore: ['hasMore', boolean()],
        lockfileSummaries: [
          'lockfileSummaries',
          array(protosScaV1LockfileDependencySummarySchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
