/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AiSastFindings, aiSastFindingsSchema } from './aiSastFindings.js';
import { SastFindings, sastFindingsSchema } from './sastFindings.js';
import { ScaFindings, scaFindingsSchema } from './scaFindings.js';

/** Response containing a paginated list of findings (either Code or Supply Chain findings) with optional filtering applied */
export interface ListFindingsResponse {
  /** A list of AI-powered scan findings that Semgrep has identified in your organization */
  aiSastFindings?: AiSastFindings;
  /** A list of Code findings that Semgrep has identified in your organization */
  sastFindings?: SastFindings;
  /** A list of Supply Chain findings that Semgrep has identified in your organization */
  scaFindings?: ScaFindings;
  additionalProperties?: Record<string, unknown>;
}

export const listFindingsResponseSchema: Schema<ListFindingsResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        aiSastFindings: ['aiSastFindings', optional(aiSastFindingsSchema)],
        sastFindings: ['sastFindings', optional(sastFindingsSchema)],
        scaFindings: ['scaFindings', optional(scaFindingsSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
