/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** A project in your organization that uses Semgrep. */
export interface ListProject {
  /** Time when this project was created. */
  createdAt?: string;
  /** The default branch in the SCM. */
  defaultBranch?: string;
  /** Unique ID of this project. */
  id: bigint;
  /** Time of latest scan, if there is one. */
  latestScanAt?: string;
  /** Name of the project. */
  name: string;
  /** The primary branch of the project, if known. */
  primaryBranch?: string;
  /** Tags associated to this project. */
  tags: string[];
  /** URL of the project, if there is one. */
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const listProjectSchema: Schema<ListProject> = typedExpandoObject(
  {
    createdAt: ['created_at', optional(string())],
    defaultBranch: ['default_branch', optional(string())],
    id: ['id', bigint()],
    latestScanAt: ['latest_scan_at', optional(string())],
    name: ['name', string()],
    primaryBranch: ['primary_branch', optional(string())],
    tags: ['tags', array(string())],
    url: ['url', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
