/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ProtosScaV1DependencyFilter,
  protosScaV1DependencyFilterSchema,
} from './protosScaV1DependencyFilter.js';

export interface ListRepositoriesForDependenciesRequest {
  /** Use cursor in response to get next page of results. */
  cursor?: bigint;
  /** Object to provide dependency details to filter by. */
  dependencyFilter?: ProtosScaV1DependencyFilter;
  /** Deployment ID (numeric). Example: `123`. Can be found at `/deployments`, or in your Settings in the web UI. */
  deploymentId: string;
  /** Number of repositories per page. Default: 5, min: 1, max: 100. */
  pageSize?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const listRepositoriesForDependenciesRequestSchema: Schema<ListRepositoriesForDependenciesRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        cursor: ['cursor', optional(bigint())],
        dependencyFilter: [
          'dependencyFilter',
          optional(protosScaV1DependencyFilterSchema),
        ],
        deploymentId: ['deploymentId', string()],
        pageSize: ['pageSize', optional(bigint())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
