/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ProtosOpenapiV1DiffScan,
  protosOpenapiV1DiffScanSchema,
} from './protosOpenapiV1DiffScan.js';
import {
  ProtosOpenapiV1FullScan,
  protosOpenapiV1FullScanSchema,
} from './protosOpenapiV1FullScan.js';

/** [Beta] Configuration of Semgrep Managed Scans for the project, if relevant. */
export interface ManagedScanConfig {
  diffScan?: ProtosOpenapiV1DiffScan;
  fullScan?: ProtosOpenapiV1FullScan;
  additionalProperties?: Record<string, unknown>;
}

export const managedScanConfigSchema: Schema<ManagedScanConfig> = lazy(() =>
  typedExpandoObject(
    {
      diffScan: ['diff_scan', optional(protosOpenapiV1DiffScanSchema)],
      fullScan: ['full_scan', optional(protosOpenapiV1FullScanSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
