/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for MetadataComponentType
 */
export enum MetadataComponentType {
  SbomMetadataComponentTypeCycloneDxV15Application = 'SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_APPLICATION',
  SbomMetadataComponentTypeCycloneDxV15Framework = 'SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_FRAMEWORK',
  SbomMetadataComponentTypeCycloneDxV15Library = 'SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_LIBRARY',
  SbomMetadataComponentTypeCycloneDxV15Container = 'SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_CONTAINER',
  SbomMetadataComponentTypeCycloneDxV15Platform = 'SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_PLATFORM',
  SbomMetadataComponentTypeCycloneDxV15OperatingSystem = 'SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_OPERATING_SYSTEM',
  SbomMetadataComponentTypeCycloneDxV15Device = 'SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_DEVICE',
  SbomMetadataComponentTypeCycloneDxV15DeviceDriver = 'SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_DEVICE_DRIVER',
  SbomMetadataComponentTypeCycloneDxV15Firmware = 'SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_FIRMWARE',
  SbomMetadataComponentTypeCycloneDxV15File = 'SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_FILE',
  SbomMetadataComponentTypeCycloneDxV15MachineLearningModel = 'SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_MACHINE_LEARNING_MODEL',
  SbomMetadataComponentTypeCycloneDxV15Data = 'SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_DATA',
}

/**
 * Schema for MetadataComponentType
 */
export const metadataComponentTypeSchema: Schema<MetadataComponentType> = stringEnum(
  MetadataComponentType
);
