/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for NewTriageReason
 */
export enum NewTriageReason {
  AcceptableRisk = 'acceptable_risk',
  FalsePositive = 'false_positive',
  NoTime = 'no_time',
  NoTriageReason = 'no_triage_reason',
  Duplicate = 'duplicate',
}

/**
 * Schema for NewTriageReason
 */
export const newTriageReasonSchema: Schema<NewTriageReason> = stringEnum(
  NewTriageReason
);
