/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for NewTriageState
 */
export enum NewTriageState {
  Ignored = 'ignored',
  Reviewing = 'reviewing',
  Fixing = 'fixing',
  Reopened = 'reopened',
  ProvisionallyIgnored = 'provisionally_ignored',
}

/**
 * Schema for NewTriageState
 */
export const newTriageStateSchema: Schema<NewTriageState> = stringEnum(
  NewTriageState
);
