/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ProductType, productTypeSchema } from './productType.js';

export interface Policy {
  /** ID of the Policy. */
  id?: string;
  /** When True, the Policy applies to all repositories. */
  isDefault?: boolean;
  /** Name of the Policy. */
  name?: string;
  /**
   * Product type the Policy applies to.
   * | value | description |
   * |-------|---------------|
   * | PRODUCT_TYPE_SAST | The product type for Code rules. |
   * | PRODUCT_TYPE_SECRETS | The product type for Secrets rules. |
   */
  productType?: ProductType;
  /** Sanitized machine-readable name of the Policy. */
  slug?: string;
  additionalProperties?: Record<string, unknown>;
}

export const policySchema: Schema<Policy> = typedExpandoObject(
  {
    id: ['id', optional(string())],
    isDefault: ['isDefault', optional(boolean())],
    name: ['name', optional(string())],
    productType: ['productType', optional(productTypeSchema)],
    slug: ['slug', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
