/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PolicyMode3
 */
export enum PolicyMode3 {
  ModeMonitor = 'MODE_MONITOR',
  ModeComment = 'MODE_COMMENT',
  ModeBlock = 'MODE_BLOCK',
  ModeDisabled = 'MODE_DISABLED',
}

/**
 * Schema for PolicyMode3
 */
export const policyMode3Schema: Schema<PolicyMode3> = stringEnum(PolicyMode3);
