/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PolicyMode1
 */
export enum PolicyMode1 {
  Monitor = 'monitor',
  Comment = 'comment',
  Block = 'block',
}

/**
 * Schema for PolicyMode1
 */
export const policyMode1Schema: Schema<PolicyMode1> = stringEnum(PolicyMode1);
