/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Reference to a policy, with some basic information. If null, then the information does not exist or lacks integrity (older or broken scans) */
export interface PolicyReference {
  /** Unique numerical identifier of the policy */
  id?: bigint;
  /** Human readable name */
  name?: string;
  /** Sanitized machine-readable name */
  slug?: string;
  additionalProperties?: Record<string, unknown>;
}

export const policyReferenceSchema: Schema<PolicyReference> = typedExpandoObject(
  {
    id: ['id', optional(bigint())],
    name: ['name', optional(string())],
    slug: ['slug', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
