/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PolicyMode
 */
export enum PolicyMode {
  ModeMonitor = 'MODE_MONITOR',
  ModeComment = 'MODE_COMMENT',
  ModeBlock = 'MODE_BLOCK',
  ModeDisabled = 'MODE_DISABLED',
}

/**
 * Schema for PolicyMode
 */
export const policyModeSchema: Schema<PolicyMode> = stringEnum(PolicyMode);
