/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Products
 */
export enum Products {
  ProductSast = 'PRODUCT_SAST',
  ProductSca = 'PRODUCT_SCA',
  ProductSecrets = 'PRODUCT_SECRETS',
  ProductAiSast = 'PRODUCT_AI_SAST',
}

/**
 * Schema for Products
 */
export const productsSchema: Schema<Products> = stringEnum(Products);
