/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ProductType
 */
export enum ProductType {
  ProductTypeSast = 'PRODUCT_TYPE_SAST',
  ProductTypeSecrets = 'PRODUCT_TYPE_SECRETS',
}

/**
 * Schema for ProductType
 */
export const productTypeSchema: Schema<ProductType> = stringEnum(ProductType);
