/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ManagedScanConfig,
  managedScanConfigSchema,
} from './managedScanConfig.js';

/** A project in your organization that uses Semgrep. */
export interface Project {
  /** Time when this project was created. */
  createdAt?: string;
  /** The default branch in the SCM. */
  defaultBranch?: string;
  /** Unique ID of this project. */
  id: bigint;
  /** Time of latest scan, if there is one. */
  latestScanAt?: string;
  /** [Beta] Configuration of Semgrep Managed Scans for the project, if relevant. */
  managedScanConfig?: ManagedScanConfig;
  /** Name of the project. */
  name: string;
  /** The primary branch of the project, if known. */
  primaryBranch?: string;
  /** Tags associated to this project. */
  tags: string[];
  /** URL of the project, if there is one. */
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const projectSchema: Schema<Project> = lazy(() =>
  typedExpandoObject(
    {
      createdAt: ['created_at', optional(string())],
      defaultBranch: ['default_branch', optional(string())],
      id: ['id', bigint()],
      latestScanAt: ['latest_scan_at', optional(string())],
      managedScanConfig: [
        'managed_scan_config',
        optional(managedScanConfigSchema),
      ],
      name: ['name', string()],
      primaryBranch: ['primary_branch', optional(string())],
      tags: ['tags', array(string())],
      url: ['url', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
