/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProtosOpenapiV1CreateTicketResponseTicketCreationFailed {
  /** The error message for the failure */
  error?: string;
  /** List of issue IDs */
  issueIds?: bigint[];
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1CreateTicketResponseTicketCreationFailedSchema: Schema<ProtosOpenapiV1CreateTicketResponseTicketCreationFailed> = typedExpandoObject(
  {
    error: ['error', optional(string())],
    issueIds: ['issue_ids', optional(array(bigint()))],
  },
  'additionalProperties',
  optional(unknown())
);
