/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ProtosAiV1AutotriageFeedback,
  protosAiV1AutotriageFeedbackSchema,
} from './protosAiV1AutotriageFeedback.js';
import { Verdict, verdictSchema } from './verdict.js';

export interface ProtosAiV1Autotriage {
  feedback?: ProtosAiV1AutotriageFeedback;
  id?: string;
  issueId?: string;
  matchBasedId?: string;
  memoryIdsReferenced?: string[];
  memoryIdsRendered?: string[];
  /** The reasoning for a false positive verdict, explaining why you might want to ignore the finding. Empty string if verdict is true positive. */
  reason?: string;
  /**
   * | value | description |
   * |-------|---------------|
   * | VERDICT_TRUE_POSITIVE |  |
   * | VERDICT_FALSE_POSITIVE |  |
   * | VERDICT_NO_VERDICT |  |
   */
  verdict?: Verdict;
  additionalProperties?: Record<string, unknown>;
}

export const protosAiV1AutotriageSchema: Schema<ProtosAiV1Autotriage> = lazy(
  () =>
    typedExpandoObject(
      {
        feedback: ['feedback', optional(protosAiV1AutotriageFeedbackSchema)],
        id: ['id', optional(string())],
        issueId: ['issueId', optional(string())],
        matchBasedId: ['matchBasedId', optional(string())],
        memoryIdsReferenced: ['memoryIdsReferenced', optional(array(string()))],
        memoryIdsRendered: ['memoryIdsRendered', optional(array(string()))],
        reason: ['reason', optional(string())],
        verdict: ['verdict', optional(verdictSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
