/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ProtosOpenapiV1CreateTicketResponseTicketCreationFailed,
  protosOpenapiV1CreateTicketResponseTicketCreationFailedSchema,
} from './protosOpenapiV1CreateTicketResponseTicketCreationFailed.js';
import {
  ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped,
  protosOpenapiV1CreateTicketResponseTicketCreationSkippedSchema,
} from './protosOpenapiV1CreateTicketResponseTicketCreationSkipped.js';
import {
  ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess,
  protosOpenapiV1CreateTicketResponseTicketCreationSuccessSchema,
} from './protosOpenapiV1CreateTicketResponseTicketCreationSuccess.js';

export interface ProtosOpenapiV1CreateTicketResponse {
  /** List of issues where ticket creation failed. This list may include issues that were skipped because they exceed the specified limit. */
  failed?: ProtosOpenapiV1CreateTicketResponseTicketCreationFailed[];
  /** List of issues that were skipped */
  skipped?: ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped[];
  /** List of successfully created tickets */
  succeeded?: ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess[];
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1CreateTicketResponseSchema: Schema<ProtosOpenapiV1CreateTicketResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        failed: [
          'failed',
          optional(
            array(protosOpenapiV1CreateTicketResponseTicketCreationFailedSchema)
          ),
        ],
        skipped: [
          'skipped',
          optional(
            array(
              protosOpenapiV1CreateTicketResponseTicketCreationSkippedSchema
            )
          ),
        ],
        succeeded: [
          'succeeded',
          optional(
            array(
              protosOpenapiV1CreateTicketResponseTicketCreationSuccessSchema
            )
          ),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
