/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProtosScaV1LockfileDependencySummary {
  /** Path to lockfile (e.g. foo/bar/package-lock.json). */
  lockfilePath?: string;
  /** Total number of dependencies in the lockfile. */
  numDependencies?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const protosScaV1LockfileDependencySummarySchema: Schema<ProtosScaV1LockfileDependencySummary> = typedExpandoObject(
  {
    lockfilePath: ['lockfilePath', optional(string())],
    numDependencies: ['numDependencies', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
