/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  CyclonedxVersion,
  cyclonedxVersionSchema,
} from './cyclonedxVersion.js';
import { Format, formatSchema } from './format.js';

export interface ProtosScaV1SbomFormatVersion {
  /**
   * CycloneDX schema version for the SBOM export. Supported: 1.4, 1.5, 1.6, 1.7. Defaults to 1.4 when unset.
   * | value | description |
   * |-------|---------------|
   * | SBOM_CYCLONE_DX_VERSION_V1_4 |  |
   * | SBOM_CYCLONE_DX_VERSION_V1_5 |  |
   * | SBOM_CYCLONE_DX_VERSION_V1_6 |  |
   * | SBOM_CYCLONE_DX_VERSION_V1_7 |  |
   */
  cyclonedxVersion?: CyclonedxVersion;
  /**
   * Format for the SBOM export.
   * | value | description |
   * |-------|---------------|
   * | SBOM_FORMAT_CYCLONEDX |  |
   */
  format?: Format;
  /** Deprecated. Use `cyclonedx_version`. Free-text CycloneDX version, e.g. "1.7". */
  version?: string;
  additionalProperties?: Record<string, unknown>;
}

export const protosScaV1SbomFormatVersionSchema: Schema<ProtosScaV1SbomFormatVersion> = typedExpandoObject(
  {
    cyclonedxVersion: ['cyclonedxVersion', optional(cyclonedxVersionSchema)],
    format: ['format', optional(formatSchema)],
    version: ['version', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
