/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProtosOpenapiV1GetBootstrapSmsVpcResponse {
  /** The AWSTemplateFormatVersion that the template conforms to */
  awsTemplateFormatVersion?: string;
  /** Template description */
  description?: string;
  /** Template metadata including version and last updated date */
  metadata?: unknown;
  /** Output values of the stack */
  outputs?: unknown;
  /** Template parameters */
  parameters?: unknown;
  /** Declaration of AWS resources */
  resources?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1GetBootstrapSmsVpcResponseSchema: Schema<ProtosOpenapiV1GetBootstrapSmsVpcResponse> = typedExpandoObject(
  {
    awsTemplateFormatVersion: ['AWSTemplateFormatVersion', optional(string())],
    description: ['Description', optional(string())],
    metadata: ['Metadata', optional(unknown())],
    outputs: ['Outputs', optional(unknown())],
    parameters: ['Parameters', optional(unknown())],
    resources: ['Resources', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
