/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ProtosOpenapiV1GetScanResponseScanMeta,
  protosOpenapiV1GetScanResponseScanMetaSchema,
} from './protosOpenapiV1GetScanResponseScanMeta.js';

export interface ProtosOpenapiV1GetScanResponse {
  /** imestamp of when the scan started. */
  completedAt?: string;
  /** The unique ID of the deployment associated with the scanned repository. */
  deploymentId?: bigint;
  /** The products used when running the scan. */
  enabledProducts?: string[];
  exitCode?: bigint;
  hasLogs?: boolean;
  /** The unique ID representing this scan. */
  id?: bigint;
  meta?: ProtosOpenapiV1GetScanResponseScanMeta;
  /** The unique ID of the repository that was scanned. */
  repositoryId?: bigint;
  /** when the scan was started */
  startedAt?: string;
  /** Miscellaneous statistics about the scan, like number of findings found and scan duration. */
  stats?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1GetScanResponseSchema: Schema<ProtosOpenapiV1GetScanResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        completedAt: ['completed_at', optional(string())],
        deploymentId: ['deployment_id', optional(bigint())],
        enabledProducts: ['enabled_products', optional(array(string()))],
        exitCode: ['exit_code', optional(bigint())],
        hasLogs: ['has_logs', optional(boolean())],
        id: ['id', optional(bigint())],
        meta: ['meta', optional(protosOpenapiV1GetScanResponseScanMetaSchema)],
        repositoryId: ['repository_id', optional(bigint())],
        startedAt: ['started_at', optional(string())],
        stats: ['stats', optional(unknown())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
