/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProtosScaV1SbomMetadataContact {
  email?: string;
  name?: string;
  phone?: string;
  additionalProperties?: Record<string, unknown>;
}

export const protosScaV1SbomMetadataContactSchema: Schema<ProtosScaV1SbomMetadataContact> = typedExpandoObject(
  {
    email: ['email', optional(string())],
    name: ['name', optional(string())],
    phone: ['phone', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
