/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ProtosScanV1ScanFindingsCounts,
  protosScanV1ScanFindingsCountsSchema,
} from './protosScanV1ScanFindingsCounts.js';
import { Status7, status7Schema } from './status7.js';

export interface ProtosScanV1ScanPublic {
  /** The scanned branch */
  branch?: string;
  /** The commit hash that was scanned */
  commit?: string;
  /** The timestamp when this scan completed (if it has completed). */
  completedAt?: string;
  /** Unique identifier for the deployment of the scan. */
  deploymentId?: string;
  /** The products used when running the scan. */
  enabledProducts?: string[];
  /** The exit_code of the scan (see https://semgrep.dev/docs/cli-reference#exit-codes) */
  exitCode?: string;
  findingsCounts?: ProtosScanV1ScanFindingsCounts;
  /** ID of the scan. */
  id?: string;
  /** Whether the scan was a full scan (true) or a diff scan (false) */
  isFullScan?: boolean;
  /** Unique identifier for the repository of the scan. */
  repositoryId?: string;
  /** The timestamp when this scan started. */
  startedAt?: string;
  /**
   * The current status of the scan
   * | value | description |
   * |-------|---------------|
   * | SCAN_STATUS_RUNNING | The scan is currently running |
   * | SCAN_STATUS_COMPLETED | The scan has completed successfully (0 or 1 exit code) |
   * | SCAN_STATUS_PENDING | The scan is queued and waiting to start |
   * | SCAN_STATUS_CANCELLED | The scan was cancelled before completion |
   * | SCAN_STATUS_ERROR | The scan has exited with a failure (exit code not 0 or 1) |
   * | SCAN_STATUS_NEVER_FINISHED | The scan did not report an error or success after over an hour |
   */
  status?: Status7;
  /** Duration of scan, in seconds */
  totalTime?: number;
  additionalProperties?: Record<string, unknown>;
}

export const protosScanV1ScanPublicSchema: Schema<ProtosScanV1ScanPublic> = lazy(
  () =>
    typedExpandoObject(
      {
        branch: ['branch', optional(string())],
        commit: ['commit', optional(string())],
        completedAt: ['completed_at', optional(string())],
        deploymentId: ['deployment_id', optional(string())],
        enabledProducts: ['enabled_products', optional(array(string()))],
        exitCode: ['exit_code', optional(string())],
        findingsCounts: [
          'findings_counts',
          optional(protosScanV1ScanFindingsCountsSchema),
        ],
        id: ['id', optional(string())],
        isFullScan: ['is_full_scan', optional(boolean())],
        repositoryId: ['repository_id', optional(string())],
        startedAt: ['started_at', optional(string())],
        status: ['status', optional(status7Schema)],
        totalTime: ['total_time', optional(number())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
