/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProtosTicketingV1ExternalTicket {
  /** Identifier of the external ticket (e.g. for Jira, something like OPS-158). */
  externalSlug?: string;
  /** Nango ticket id */
  id?: string;
  /** Semgrep issue ids that are linked to this external ticket */
  linkedIssueIds?: string[];
  /** URL of the external ticket. */
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const protosTicketingV1ExternalTicketSchema: Schema<ProtosTicketingV1ExternalTicket> = typedExpandoObject(
  {
    externalSlug: ['externalSlug', optional(string())],
    id: ['id', optional(string())],
    linkedIssueIds: ['linkedIssueIds', optional(array(string()))],
    url: ['url', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
