/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProtosScaV1RepositoryDependencySummary {
  /**
   * True if the repository has been scanned with the `hasPathToTransitivityInScans` feature flag
   *  which means it will have dependency graph data in DGraph available to query
   */
  hasDependencyPathScan?: boolean;
  /** ID of repository. */
  id?: bigint;
  /** Name of repository. */
  name?: string;
  /** Total number of dependencies in the repository. */
  numDependencies?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const protosScaV1RepositoryDependencySummarySchema: Schema<ProtosScaV1RepositoryDependencySummary> = typedExpandoObject(
  {
    hasDependencyPathScan: ['hasDependencyPathScan', optional(boolean())],
    id: ['id', optional(bigint())],
    name: ['name', optional(string())],
    numDependencies: ['numDependencies', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
