/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Rule, ruleSchema } from './rule.js';

export interface ProtosOpenapiV1UpdatePolicyResponse {
  /** Policy ID (numeric). Example: `456`. Can be found at `/deployments/{deploymentId}/policies`. */
  policyId?: string;
  updatedRule?: Rule;
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1UpdatePolicyResponseSchema: Schema<ProtosOpenapiV1UpdatePolicyResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        policyId: ['policyId', optional(string())],
        updatedRule: ['updatedRule', optional(ruleSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
