/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProtosOpenapiV1LinkTicketResponse {
  /** The external slug identifier for the ticket (e.g. SEC-123) */
  externalSlug?: string;
  /** List of finding IDs that were successfully linked to the ticket */
  linkedIssueIds?: string[];
  /** List of finding IDs where an existing ticket link was replaced */
  replacedIssueIds?: string[];
  /** The internal ID of the linked ticket record */
  ticketId?: bigint;
  /** The URL of the linked ticket */
  ticketUrl?: string;
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1LinkTicketResponseSchema: Schema<ProtosOpenapiV1LinkTicketResponse> = typedExpandoObject(
  {
    externalSlug: ['external_slug', optional(string())],
    linkedIssueIds: ['linked_issue_ids', optional(array(string()))],
    replacedIssueIds: ['replaced_issue_ids', optional(array(string()))],
    ticketId: ['ticket_id', optional(bigint())],
    ticketUrl: ['ticket_url', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
