/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ProtosSecretsV1SecretsFinding,
  protosSecretsV1SecretsFindingSchema,
} from './protosSecretsV1SecretsFinding.js';

export interface ProtosOpenapiV1ListSecretsPathResponse {
  /** Cursor to paginate through the results. */
  cursor?: string;
  /** List of Secrets associated with the given Deployment. */
  findings?: ProtosSecretsV1SecretsFinding[];
  /** Cursor to paginate backwards through the results. */
  previous?: string;
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1ListSecretsPathResponseSchema: Schema<ProtosOpenapiV1ListSecretsPathResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        cursor: ['cursor', optional(string())],
        findings: [
          'findings',
          optional(array(protosSecretsV1SecretsFindingSchema)),
        ],
        previous: ['previous', optional(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
