/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Specific location in a file. */
export interface ProtosScaV1CodeLocation {
  /** Timestamp when code file was last modified, if available. */
  committedAt?: string;
  /** Ending column number (1 indexed). */
  endCol?: string;
  /** Ending line number (1 indexed). */
  endLine?: string;
  /** Path to a file. */
  path?: string;
  /** Starting column number (1 indexed). */
  startCol?: string;
  /** Starting line number (1 indexed). */
  startLine?: string;
  /** URL to code location if available, otherwise empty. */
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const protosScaV1CodeLocationSchema: Schema<ProtosScaV1CodeLocation> = typedExpandoObject(
  {
    committedAt: ['committedAt', optional(string())],
    endCol: ['endCol', optional(string())],
    endLine: ['endLine', optional(string())],
    path: ['path', optional(string())],
    startCol: ['startCol', optional(string())],
    startLine: ['startLine', optional(string())],
    url: ['url', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
