/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped {
  /** List of issue IDs */
  issueIds?: bigint[];
  /** The reason why the issue was skipped */
  reason?: string;
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1CreateTicketResponseTicketCreationSkippedSchema: Schema<ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped> = typedExpandoObject(
  {
    issueIds: ['issue_ids', optional(array(bigint()))],
    reason: ['reason', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
