/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** A specific dependency. */
export interface ProtosScaV1Dependency {
  /** String identifier of dependency */
  name?: string;
  /** Version specifier of dependency. */
  versionSpecifier?: string;
  additionalProperties?: Record<string, unknown>;
}

export const protosScaV1DependencySchema: Schema<ProtosScaV1Dependency> = typedExpandoObject(
  {
    name: ['name', optional(string())],
    versionSpecifier: ['versionSpecifier', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
