/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProtosOpenapiV1FullScan {
  /** When true, weekly full scans are enabled. */
  enabled?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1FullScanSchema: Schema<ProtosOpenapiV1FullScan> = typedExpandoObject(
  { enabled: ['enabled', optional(boolean())] },
  'additionalProperties',
  optional(unknown())
);
