/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ScmType, scmTypeSchema } from './scmType.js';
import { Visibility, visibilitySchema } from './visibility.js';

/** Repository where the finding was detected. */
export interface ProtosSecretsV1SecretsFindingRepository {
  /** Repository name */
  name?: string;
  /**
   * Provider for the finding (e.g. GitHub, GitLab, GHE, etc).
   * | value | description |
   * |-------|---------------|
   * | SCM_TYPE_GITHUB | GitHub Cloud |
   * | SCM_TYPE_GITHUB_ENTERPRISE | GitHub Enterprise |
   * | SCM_TYPE_GITLAB | GitLab Cloud |
   * | SCM_TYPE_GITLAB_SELFMANAGED | GitLab Self-Managed |
   * | SCM_TYPE_BITBUCKET | Bitbucket Cloud |
   * | SCM_TYPE_BITBUCKET_DATACENTER | Bitbucket Data Center |
   * | SCM_TYPE_AZURE_DEVOPS | Azure DevOps |
   * | SCM_TYPE_UNKNOWN |  |
   * | SCM_TYPE_HARNESS | Harness |
   */
  scmType?: ScmType;
  /** URL to the repository where the finding was detected. */
  url?: string;
  /**
   * Repository visbility (e.g. public, private, unknown).
   * | value | description |
   * |-------|---------------|
   * | REPOSITORY_VISIBILITY_PUBLIC |  |
   * | REPOSITORY_VISIBILITY_PRIVATE |  |
   * | REPOSITORY_VISIBILITY_UNKNOWN |  |
   */
  visibility?: Visibility;
  additionalProperties?: Record<string, unknown>;
}

export const protosSecretsV1SecretsFindingRepositorySchema: Schema<ProtosSecretsV1SecretsFindingRepository> = typedExpandoObject(
  {
    name: ['name', optional(string())],
    scmType: ['scmType', optional(scmTypeSchema)],
    url: ['url', optional(string())],
    visibility: ['visibility', optional(visibilitySchema)],
  },
  'additionalProperties',
  optional(unknown())
);
