/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProtosSecretsV1HistoricalInfo {
  /**
   * Git blob at which the finding is present. Sent in addition to the commit
   *  since some SCMs have permalinks which use the blob sha, so this information
   *  is useful when generating links back to the SCM.
   */
  gitBlob?: string;
  /**
   * Git commit at which the finding is present. Used by "historical" scans,
   *  which scan non-HEAD commits in the git history. Relevant for finding, e.g.,
   *  secrets which are buried in the git history which we wouldn't find at HEAD
   */
  gitCommit?: string;
  gitCommitTimestamp?: string;
  additionalProperties?: Record<string, unknown>;
}

export const protosSecretsV1HistoricalInfoSchema: Schema<ProtosSecretsV1HistoricalInfo> = typedExpandoObject(
  {
    gitBlob: ['gitBlob', optional(string())],
    gitCommit: ['gitCommit', optional(string())],
    gitCommitTimestamp: ['gitCommitTimestamp', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
