/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Policy, policySchema } from './policy.js';

export interface ProtosOpenapiV1ListPoliciesResponse {
  /** List of Policies associated with the given Deployment. */
  policies?: Policy[];
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1ListPoliciesResponseSchema: Schema<ProtosOpenapiV1ListPoliciesResponse> = lazy(
  () =>
    typedExpandoObject(
      { policies: ['policies', optional(array(policySchema))] },
      'additionalProperties',
      optional(unknown())
    )
);
