/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess {
  /** The external slug identifier for the ticket */
  externalSlug?: string;
  /** List of issue IDs */
  issueIds?: bigint[];
  /** The ID of the created ticket */
  ticketId?: bigint;
  /** The URL of the created ticket */
  ticketUrl?: string;
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1CreateTicketResponseTicketCreationSuccessSchema: Schema<ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess> = typedExpandoObject(
  {
    externalSlug: ['external_slug', optional(string())],
    issueIds: ['issue_ids', optional(array(bigint()))],
    ticketId: ['ticket_id', optional(bigint())],
    ticketUrl: ['ticket_url', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
