/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Individual package filter with optional version bounds. */
export interface ProtosScaV1PackageFilter {
  /** When true, name must match exactly. When false (default), name is fuzzy-matched (contains). */
  exactNameMatch?: boolean;
  /**
   * Exact version match (e.g. "1.0.0").
   *  Takes precedence over version bounds if set.
   */
  exactVersion?: string;
  /** Exact package name (e.g. lodash). */
  name?: string;
  /**
   * Lower bound version constraint (e.g. ">=1.0.0").
   *  Ignored if exact_version is set.
   */
  versionLowerBound?: string;
  /**
   * Upper bound version constraint (e.g. "<2.0.0").
   *  Ignored if exact_version is set.
   */
  versionUpperBound?: string;
  additionalProperties?: Record<string, unknown>;
}

export const protosScaV1PackageFilterSchema: Schema<ProtosScaV1PackageFilter> = typedExpandoObject(
  {
    exactNameMatch: ['exactNameMatch', optional(boolean())],
    exactVersion: ['exactVersion', optional(string())],
    name: ['name', optional(string())],
    versionLowerBound: ['versionLowerBound', optional(string())],
    versionUpperBound: ['versionUpperBound', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
