/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Deployment, deploymentSchema } from './deployment.js';

export interface ProtosOpenapiV1ListDeploymentsResponse {
  /** Return the deployment the supplied token can access. */
  deployments?: Deployment[];
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1ListDeploymentsResponseSchema: Schema<ProtosOpenapiV1ListDeploymentsResponse> = lazy(
  () =>
    typedExpandoObject(
      { deployments: ['deployments', optional(array(deploymentSchema))] },
      'additionalProperties',
      optional(unknown())
    )
);
