/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Ecosystem1, ecosystem1Schema } from './ecosystem1.js';
import {
  ProtosScaV1CodeLocation,
  protosScaV1CodeLocationSchema,
} from './protosScaV1CodeLocation.js';
import {
  ProtosScaV1Dependency,
  protosScaV1DependencySchema,
} from './protosScaV1Dependency.js';
import { Transitivity1, transitivity1Schema } from './transitivity1.js';

export interface ProtosScaV1FoundDependency {
  /** Path and line number dependency is declared in. */
  definedAt?: ProtosScaV1CodeLocation;
  /**
   * The ecosystem the dependency is in (e.g. pypi, npm, etc).
   * | value | description |
   * |-------|---------------|
   * | no_package_manager |  |
   * | npm |  |
   * | pypi |  |
   * | gomod |  |
   * | cargo |  |
   * | maven |  |
   * | gem |  |
   * | composer |  |
   * | nuget |  |
   * | pub |  |
   * | swiftpm |  |
   * | hex |  |
   * | cocoapods |  |
   * | mix |  |
   * | opam |  |
   */
  ecosystem?: Ecosystem1;
  /** Licenses the dependency is using. */
  licenses?: string[];
  /** Path to the manifest file that defines the subproject containing this dependency */
  manifestDefinition?: ProtosScaV1CodeLocation;
  /** What the dependency is. */
  mPackage?: ProtosScaV1Dependency;
  /** ID of repository dependency is found in. */
  repositoryId?: string;
  /** The resolved URL of the dependency. Could point to a compressed source code directory (e.g. tarball), source code repository, or a package manager cache directory. May be empty if the package manager doesn't supply a URL. */
  resolvedUrl?: string;
  /**
   * Whether dependency is direct or transitive.
   * | value | description |
   * |-------|---------------|
   * | UNKNOWN_TRANSITIVITY |  |
   * | TRANSITIVE |  |
   * | DIRECT |  |
   */
  transitivity?: Transitivity1;
  additionalProperties?: Record<string, unknown>;
}

export const protosScaV1FoundDependencySchema: Schema<ProtosScaV1FoundDependency> = lazy(
  () =>
    typedExpandoObject(
      {
        definedAt: ['definedAt', optional(protosScaV1CodeLocationSchema)],
        ecosystem: ['ecosystem', optional(ecosystem1Schema)],
        licenses: ['licenses', optional(array(string()))],
        manifestDefinition: [
          'manifestDefinition',
          optional(protosScaV1CodeLocationSchema),
        ],
        mPackage: ['package', optional(protosScaV1DependencySchema)],
        repositoryId: ['repositoryId', optional(string())],
        resolvedUrl: ['resolvedUrl', optional(string())],
        transitivity: ['transitivity', optional(transitivity1Schema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
