/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProtosScanV1ScanFindingsCounts {
  /** Total number of Code findings in the scan */
  code?: string;
  /** Total number of Secrets findings in the scan */
  secrets?: string;
  /** Total number of Supply Chain findings in the scan */
  supplyChain?: string;
  /** Total number of findings in the scan */
  total?: string;
  additionalProperties?: Record<string, unknown>;
}

export const protosScanV1ScanFindingsCountsSchema: Schema<ProtosScanV1ScanFindingsCounts> = typedExpandoObject(
  {
    code: ['code', optional(string())],
    secrets: ['secrets', optional(string())],
    supplyChain: ['supply_chain', optional(string())],
    total: ['total', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
