/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProtosOpenapiV1DiffScan {
  /** When true, diff-aware scans are enabled for the project. */
  enabled?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1DiffScanSchema: Schema<ProtosOpenapiV1DiffScan> = typedExpandoObject(
  { enabled: ['enabled', optional(boolean())] },
  'additionalProperties',
  optional(unknown())
);
