/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ProtosScaV1SbomMetadataContact,
  protosScaV1SbomMetadataContactSchema,
} from './protosScaV1SbomMetadataContact.js';

export interface ProtosScaV1SbomMetadataSupplier {
  contact?: ProtosScaV1SbomMetadataContact;
  name?: string;
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const protosScaV1SbomMetadataSupplierSchema: Schema<ProtosScaV1SbomMetadataSupplier> = lazy(
  () =>
    typedExpandoObject(
      {
        contact: ['contact', optional(protosScaV1SbomMetadataContactSchema)],
        name: ['name', optional(string())],
        url: ['url', optional(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
