/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Ecosystem, ecosystemSchema } from './ecosystem.js';
import {
  LicensePolicySettings,
  licensePolicySettingsSchema,
} from './licensePolicySettings.js';
import {
  ProtosScaV1PackageFilter,
  protosScaV1PackageFilterSchema,
} from './protosScaV1PackageFilter.js';
import { Transitivity, transitivitySchema } from './transitivity.js';

/** Object to provide dependency details to filter by. */
export interface ProtosScaV1DependencyFilter {
  /**
   * Filter by ecosystem (e.g. npm, pypi, etc).
   * | value | description |
   * |-------|---------------|
   * | no_package_manager |  |
   * | npm |  |
   * | pypi |  |
   * | gomod |  |
   * | cargo |  |
   * | maven |  |
   * | gem |  |
   * | composer |  |
   * | nuget |  |
   * | pub |  |
   * | swiftpm |  |
   * | hex |  |
   * | cocoapods |  |
   * | mix |  |
   * | opam |  |
   */
  ecosystem?: Ecosystem;
  /** Filter by license (e.g. MIT). */
  license?: string[];
  /**
   * Filter by license policy setting outcome.
   * | value | description |
   * |-------|---------------|
   * | LICENSE_POLICY_SETTING_ALLOW |  |
   * | LICENSE_POLICY_SETTING_COMMENT |  |
   * | LICENSE_POLICY_SETTING_BLOCK |  |
   */
  licensePolicySettings?: LicensePolicySettings;
  /** Filter by path to the lockfile (e.g. `foo/bar/package-lock.json`). */
  lockfilePath?: string;
  /** Deprecated - use package_filters instead. Filter by dependency name (e.g. lodash). */
  name?: string;
  /** Multiple package filters with exact name matching and version bounds. */
  packageFilters?: ProtosScaV1PackageFilter[];
  /**
   * Repository IDs (numeric) to filter by. Omit if the endpoint has Repository ID as a path parameter.
   *  Use Projects endpoints to retrieve Repository IDs.
   */
  repositoryId?: bigint[];
  /**
   * Filter by transitivity.
   * | value | description |
   * |-------|---------------|
   * | UNKNOWN_TRANSITIVITY |  |
   * | TRANSITIVE |  |
   * | DIRECT |  |
   */
  transitivity?: Transitivity;
  /** Deprecated - use package_filters instead. Filter by dependency version (e.g. 1.0.1). */
  version?: string;
  additionalProperties?: Record<string, unknown>;
}

export const protosScaV1DependencyFilterSchema: Schema<ProtosScaV1DependencyFilter> = lazy(
  () =>
    typedExpandoObject(
      {
        ecosystem: ['ecosystem', optional(ecosystemSchema)],
        license: ['license', optional(array(string()))],
        licensePolicySettings: [
          'licensePolicySettings',
          optional(licensePolicySettingsSchema),
        ],
        lockfilePath: ['lockfilePath', optional(string())],
        name: ['name', optional(string())],
        packageFilters: [
          'packageFilters',
          optional(array(protosScaV1PackageFilterSchema)),
        ],
        repositoryId: ['repositoryId', optional(array(bigint()))],
        transitivity: ['transitivity', optional(transitivitySchema)],
        version: ['version', optional(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
