/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Policy, policySchema } from './policy.js';
import { Rule, ruleSchema } from './rule.js';

export interface ProtosOpenapiV1ListPolicyRulesResponse {
  /** Cursor to paginate through the rules. */
  cursor?: string;
  policy?: Policy;
  /** List of Rules for the given Policy. */
  rules?: Rule[];
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1ListPolicyRulesResponseSchema: Schema<ProtosOpenapiV1ListPolicyRulesResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        cursor: ['cursor', optional(string())],
        policy: ['policy', optional(policySchema)],
        rules: ['rules', optional(array(ruleSchema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
