/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProtosOpenapiV1GetScanResponseScanMeta {
  /** What triggered this scan, if applicable. */
  mTrue?: string;
  /** The branch that was scanned, if applicable. */
  branch?: string;
  /** The commit SHA associated with the scan, if applicable. */
  commit?: string;
  /** The path of the configuration file used for this scan, if applicable. */
  config?: string;
  /** The URL of the scanned repository, if applicable. */
  repoUrl?: string;
  /** The URL of the CI job that ran the scan, if applicable. */
  ciJobUrl?: string;
  /** The name and organization of the scanned repository, if applicable. */
  repository?: string;
  /** The commit message associated with the scan, if applicable. */
  commitTitle?: string;
  /** The ID of the pull request associated with the scan, if applicable. */
  pullRequestId?: string;
  /** The title of the pull request associated with the scan if applicable. */
  pullRequestTitle?: string;
  /** The name of the author of the commit associated with the scan, if applicable. */
  commitAuthorName?: string;
  /** The avatar image url of the author of the commit associated with the scan, if applicable. */
  commitAuthorImageUrl?: string;
  /** The email of the author of the commit associated with the scan, if applicable. */
  commitAuthorEmail?: string;
  /** The username of the author of the commit associated with the scan, if applicable. */
  commitAuthorUsername?: string;
  /** The username of the author of the pull request associated with the scan, if applicable. */
  pullRequestAuthorUsername?: string;
  /** The avatar image url of the author of the pull request associated with the scan, if applicable. */
  pullRequestAuthorImageUrl?: string;
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1GetScanResponseScanMetaSchema: Schema<ProtosOpenapiV1GetScanResponseScanMeta> = typedExpandoObject(
  {
    mTrue: ['true', optional(string())],
    branch: ['branch', optional(string())],
    commit: ['commit', optional(string())],
    config: ['config', optional(string())],
    repoUrl: ['repo_url', optional(string())],
    ciJobUrl: ['ci_job_url', optional(string())],
    repository: ['repository', optional(string())],
    commitTitle: ['commit_title', optional(string())],
    pullRequestId: ['pull_request_id', optional(string())],
    pullRequestTitle: ['pull_request_title', optional(string())],
    commitAuthorName: ['commit_author_name', optional(string())],
    commitAuthorImageUrl: ['commit_author_image_url', optional(string())],
    commitAuthorEmail: ['commit_author_email', optional(string())],
    commitAuthorUsername: ['commit_author_username', optional(string())],
    pullRequestAuthorUsername: [
      'pull_request_author_username',
      optional(string()),
    ],
    pullRequestAuthorImageUrl: [
      'pull_request_author_image_url',
      optional(string()),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
