/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Rating, ratingSchema } from './rating.js';

export interface ProtosAiV1AutotriageFeedback {
  autotriageId?: string;
  note?: string;
  /**
   * | value | description |
   * |-------|---------------|
   * | RATING_GOOD | Autotriage rated positively by a user. |
   * | RATING_BAD | Autotriage rated negatively by a user. |
   */
  rating?: Rating;
  additionalProperties?: Record<string, unknown>;
}

export const protosAiV1AutotriageFeedbackSchema: Schema<ProtosAiV1AutotriageFeedback> = typedExpandoObject(
  {
    autotriageId: ['autotriageId', optional(string())],
    note: ['note', optional(string())],
    rating: ['rating', optional(ratingSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
