/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProtosOpenapiV1UnlinkTicketResponse {
  /** List of finding IDs that were successfully unlinked from their tickets */
  unlinkedIssueIds?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1UnlinkTicketResponseSchema: Schema<ProtosOpenapiV1UnlinkTicketResponse> = typedExpandoObject(
  { unlinkedIssueIds: ['unlinked_issue_ids', optional(array(string()))] },
  'additionalProperties',
  optional(unknown())
);
