/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Confidence7, confidence7Schema } from './confidence7.js';
import { Mode, modeSchema } from './mode.js';
import {
  ProtosAiV1Autotriage,
  protosAiV1AutotriageSchema,
} from './protosAiV1Autotriage.js';
import {
  ProtosCommonV1ReviewComment,
  protosCommonV1ReviewCommentSchema,
} from './protosCommonV1ReviewComment.js';
import {
  ProtosSecretsV1HistoricalInfo,
  protosSecretsV1HistoricalInfoSchema,
} from './protosSecretsV1HistoricalInfo.js';
import {
  ProtosSecretsV1SecretsFindingRepository,
  protosSecretsV1SecretsFindingRepositorySchema,
} from './protosSecretsV1SecretsFindingRepository.js';
import {
  ProtosTicketingV1ExternalTicket,
  protosTicketingV1ExternalTicketSchema,
} from './protosTicketingV1ExternalTicket.js';
import { Severity4, severity4Schema } from './severity4.js';
import { Status6, status6Schema } from './status6.js';
import {
  ValidationState2,
  validationState2Schema,
} from './validationState2.js';

/** A Finding represents a single secret finding. */
export interface ProtosSecretsV1SecretsFinding {
  /**
   * * Autotriage info for the finding.
   *  This is used for the Generic Secrets Detection project, for
   *  autotriaging secrets findings with LLMs
   */
  autotriage?: ProtosAiV1Autotriage;
  /**
   * Confidence of the finding.
   * | value | description |
   * |-------|---------------|
   * | CONFIDENCE_HIGH |  |
   * | CONFIDENCE_MEDIUM |  |
   * | CONFIDENCE_LOW |  |
   */
  confidence?: Confidence7;
  /** Creation timestamp. */
  createdAt?: string;
  /** The external ticket reference */
  externalTicket?: ProtosTicketingV1ExternalTicket;
  /** File path where the finding was detected. */
  findingPath?: string;
  /** URL to the file where the finding was detected. */
  findingPathUrl?: string;
  /** Historical scanning info for the finding. */
  historicalInfo?: ProtosSecretsV1HistoricalInfo;
  /** ID of the finding. */
  id?: string;
  /**
   * The behavior of the finding reporting: Monitor / Comment / Block.
   * | value | description |
   * |-------|---------------|
   * | MODE_MONITOR | Monitor mode, silently report findings |
   * | MODE_COMMENT | Comment mode, leaves PR comments but does not block |
   * | MODE_BLOCK | Block mode, leaves PR comments and blocks PR |
   * | MODE_DISABLED | Disabled mode, not active |
   */
  mode?: Mode;
  /** Branch where the finding was detected. */
  ref?: string;
  /** URL to the branch where the finding was detected. */
  refUrl?: string;
  /** Repository where the finding was detected. */
  repository?: ProtosSecretsV1SecretsFindingRepository;
  /** List of external review comment information associated with a finding */
  reviewComments?: ProtosCommonV1ReviewComment[];
  /** ID of the rule that triggered the finding. */
  ruleHashId?: string;
  /**
   * Severity of the finding.
   * | value | description |
   * |-------|---------------|
   * | SEVERITY_HIGH |  |
   * | SEVERITY_MEDIUM |  |
   * | SEVERITY_LOW |  |
   * | SEVERITY_CRITICAL |  |
   */
  severity?: Severity4;
  /**
   * Status of the finding.
   * | value | description |
   * |-------|---------------|
   * | FINDING_STATUS_OPEN |  |
   * | FINDING_STATUS_IGNORED |  |
   * | FINDING_STATUS_FIXED |  |
   * | FINDING_STATUS_REMOVED |  |
   * | FINDING_STATUS_UNKNOWN |  |
   * | FINDING_STATUS_PROVISIONALLY_IGNORED |  |
   */
  status?: Status6;
  /** Service type for the secrets finding (e.g. AWS, GitHub, GitLab, etc). */
  type?: string;
  /** Update timestamp. */
  updatedAt?: string;
  /**
   * Whether the finding was validated or not.
   * | value | description |
   * |-------|---------------|
   * | VALIDATION_STATE_CONFIRMED_VALID |  |
   * | VALIDATION_STATE_CONFIRMED_INVALID |  |
   * | VALIDATION_STATE_VALIDATION_ERROR |  |
   * | VALIDATION_STATE_NO_VALIDATOR |  |
   */
  validationState?: ValidationState2;
  additionalProperties?: Record<string, unknown>;
}

export const protosSecretsV1SecretsFindingSchema: Schema<ProtosSecretsV1SecretsFinding> = lazy(
  () =>
    typedExpandoObject(
      {
        autotriage: ['autotriage', optional(protosAiV1AutotriageSchema)],
        confidence: ['confidence', optional(confidence7Schema)],
        createdAt: ['createdAt', optional(string())],
        externalTicket: [
          'externalTicket',
          optional(protosTicketingV1ExternalTicketSchema),
        ],
        findingPath: ['findingPath', optional(string())],
        findingPathUrl: ['findingPathUrl', optional(string())],
        historicalInfo: [
          'historicalInfo',
          optional(protosSecretsV1HistoricalInfoSchema),
        ],
        id: ['id', optional(string())],
        mode: ['mode', optional(modeSchema)],
        ref: ['ref', optional(string())],
        refUrl: ['refUrl', optional(string())],
        repository: [
          'repository',
          optional(protosSecretsV1SecretsFindingRepositorySchema),
        ],
        reviewComments: [
          'reviewComments',
          optional(array(protosCommonV1ReviewCommentSchema)),
        ],
        ruleHashId: ['ruleHashId', optional(string())],
        severity: ['severity', optional(severity4Schema)],
        status: ['status', optional(status6Schema)],
        type: ['type', optional(string())],
        updatedAt: ['updatedAt', optional(string())],
        validationState: ['validationState', optional(validationState2Schema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
