/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ProtosScanV1ScanPublic,
  protosScanV1ScanPublicSchema,
} from './protosScanV1ScanPublic.js';

export interface ProtosOpenapiV1SearchScansResponse {
  /** Cursor to retrieve the next page of results. */
  cursor?: string;
  /** List of scans. */
  scans?: ProtosScanV1ScanPublic[];
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1SearchScansResponseSchema: Schema<ProtosOpenapiV1SearchScansResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        cursor: ['cursor', optional(string())],
        scans: ['scans', optional(array(protosScanV1ScanPublicSchema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
