/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ProtosOpenapiV1DeleteTicketResponse {
  /** List of issue IDs unlinked from ticket */
  issueIds?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const protosOpenapiV1DeleteTicketResponseSchema: Schema<ProtosOpenapiV1DeleteTicketResponse> = typedExpandoObject(
  { issueIds: ['issueIds', optional(array(string()))] },
  'additionalProperties',
  optional(unknown())
);
