/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Rating
 */
export enum Rating {
  RatingGood = 'RATING_GOOD',
  RatingBad = 'RATING_BAD',
}

/**
 * Schema for Rating
 */
export const ratingSchema: Schema<Rating> = stringEnum(Rating);
