/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Reachability
 */
export enum Reachability {
  EnumNoReachabilityAnalysis = 'no reachability analysis',
  Reachable = 'reachable',
  EnumAlwaysReachable = 'always reachable',
  EnumConditionallyReachable = 'conditionally reachable',
  Unreachable = 'unreachable',
}

/**
 * Schema for Reachability
 */
export const reachabilitySchema: Schema<Reachability> = stringEnum(
  Reachability
);
