/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for RepositoryVisibility
 */
export enum RepositoryVisibility {
  Public = 'public',
  Private = 'private',
  Unknown = 'unknown',
}

/**
 * Schema for RepositoryVisibility
 */
export const repositoryVisibilitySchema: Schema<RepositoryVisibility> = stringEnum(
  RepositoryVisibility
);
