/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** External review comment information associated with a finding */
export interface ReviewComment {
  /** External ID of the review comment or discussion thread */
  externalDiscussionId?: string;
  /** External ID of the specific note in the review comment discussion thread. Only applicable for GitLab.com, GitLab Self-Managed and Azure DevOps */
  externalNoteId?: string;
  additionalProperties?: Record<string, unknown>;
}

export const reviewCommentSchema: Schema<ReviewComment> = typedExpandoObject(
  {
    externalDiscussionId: ['external_discussion_id', optional(string())],
    externalNoteId: ['external_note_id', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
