/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Risk
 */
export enum Risk {
  High = 'high',
  Low = 'low',
  Neutral = 'neutral',
}

/**
 * Schema for Risk
 */
export const riskSchema: Schema<Risk> = stringEnum(Risk);
