/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Confidence, confidenceSchema } from './confidence.js';
import { PolicyMode, policyModeSchema } from './policyMode.js';
import { Severity, severitySchema } from './severity.js';
import { Source, sourceSchema } from './source.js';

export interface Rule {
  /** Category the Rule is associated with. */
  category?: string;
  /**
   * Confidence based on the Rule's false-positive rate.
   * | value | description |
   * |-------|---------------|
   * | CONFIDENCE_HIGH |  |
   * | CONFIDENCE_MEDIUM |  |
   * | CONFIDENCE_LOW |  |
   */
  confidence?: Confidence;
  /** The CWE associated with the Rule. */
  cweCategories?: string[];
  /** When True, the secrets rule has validators. */
  hasValidators?: boolean;
  /** ID of the Rule. */
  id?: string;
  /** Languages the Rule applies to. */
  languages?: string[];
  /** Timestamp of when the Rule was last changed. */
  lastChangeAt?: string;
  /** Username of who last changed the Rule. */
  lastChangeBy?: string;
  /** Owasp categories the Rule is associated with. */
  owaspCategories?: string[];
  /** Full path of the Rule. */
  path?: string;
  /**
   * Mode behavior: Monitor / Comment / Block / Disabled
   * | value | description |
   * |-------|---------------|
   * | MODE_MONITOR | Monitor mode, silently report findings |
   * | MODE_COMMENT | Comment mode, leaves PR comments but does not block |
   * | MODE_BLOCK | Block mode, leaves PR comments and blocks PR |
   * | MODE_DISABLED | Disabled mode, not active |
   */
  policyMode?: PolicyMode;
  /** The Registry maintainer associated with the Rule (if applicable). */
  registryMaintainer?: string;
  /** Rulesets to which the Rule belongs (if applicable). */
  rulesets?: string[];
  /** The secret type (if applicable). */
  secretType?: string;
  /**
   * Severity level ("seriousness" of the finding)
   * | value | description |
   * |-------|---------------|
   * | SEVERITY_HIGH |  |
   * | SEVERITY_MEDIUM |  |
   * | SEVERITY_LOW |  |
   * | SEVERITY_CRITICAL |  |
   */
  severity?: Severity;
  /**
   * Source of the Rule
   * | value | description |
   * |-------|---------------|
   * | SOURCE_PRO | From Pro rules |
   * | SOURCE_COMMUNITY | From Semgrep Community rules |
   * | SOURCE_CUSTOM | From Custom rules |
   */
  source?: Source;
  /** Technologies the Rule is associated with. */
  technologies?: string[];
  /** The URL of the Rule. */
  url?: string;
  /** Vulnerability classes the Rule is associated with. */
  vulnerabilityClass?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const ruleSchema: Schema<Rule> = typedExpandoObject(
  {
    category: ['category', optional(string())],
    confidence: ['confidence', optional(confidenceSchema)],
    cweCategories: ['cweCategories', optional(array(string()))],
    hasValidators: ['hasValidators', optional(boolean())],
    id: ['id', optional(string())],
    languages: ['languages', optional(array(string()))],
    lastChangeAt: ['lastChangeAt', optional(string())],
    lastChangeBy: ['lastChangeBy', optional(string())],
    owaspCategories: ['owaspCategories', optional(array(string()))],
    path: ['path', optional(string())],
    policyMode: ['policyMode', optional(policyModeSchema)],
    registryMaintainer: ['registryMaintainer', optional(string())],
    rulesets: ['rulesets', optional(array(string()))],
    secretType: ['secretType', optional(string())],
    severity: ['severity', optional(severitySchema)],
    source: ['source', optional(sourceSchema)],
    technologies: ['technologies', optional(array(string()))],
    url: ['url', optional(string())],
    vulnerabilityClass: ['vulnerabilityClass', optional(array(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
