/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** AI-generated explanation of why a rule flagged this specific code */
export interface RuleExplanation {
  /** Detailed explanation of why this rule flagged the code, including context about the security issue and why it applies to this specific code. AI generated content, review carefully */
  explanation?: string;
  /** A concise summary of the rule explanation. May not be present for all findings */
  summary?: string;
  additionalProperties?: Record<string, unknown>;
}

export const ruleExplanationSchema: Schema<RuleExplanation> = typedExpandoObject(
  {
    explanation: ['explanation', optional(string())],
    summary: ['summary', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
