/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { SastFinding, sastFindingSchema } from './sastFinding.js';

/** A list of Code findings that Semgrep has identified in your organization */
export interface SastFindings {
  /** A list of Code findings. */
  findings?: SastFinding[];
  additionalProperties?: Record<string, unknown>;
}

export const sastFindingsSchema: Schema<SastFindings> = lazy(() =>
  typedExpandoObject(
    { findings: ['findings', optional(array(sastFindingSchema))] },
    'additionalProperties',
    optional(unknown())
  )
);
