/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for SbomOutputFormat
 */
export enum SbomOutputFormat {
  SbomOutputFormatJson = 'SBOM_OUTPUT_FORMAT_JSON',
  SbomOutputFormatCyclonedx = 'SBOM_OUTPUT_FORMAT_CYCLONEDX',
}

/**
 * Schema for SbomOutputFormat
 */
export const sbomOutputFormatSchema: Schema<SbomOutputFormat> = stringEnum(
  SbomOutputFormat
);
