/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ScaFinding, scaFindingSchema } from './scaFinding.js';

/** A list of Supply Chain findings that Semgrep has identified in your organization */
export interface ScaFindings {
  /** A list of Supply Chain findings. */
  findings?: ScaFinding[];
  additionalProperties?: Record<string, unknown>;
}

export const scaFindingsSchema: Schema<ScaFindings> = lazy(() =>
  typedExpandoObject(
    { findings: ['findings', optional(array(scaFindingSchema))] },
    'additionalProperties',
    optional(unknown())
  )
);
