/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Confidence1, confidence1Schema } from './confidence1.js';
import { EpssScore, epssScoreSchema } from './epssScore.js';
import { ExternalTicket, externalTicketSchema } from './externalTicket.js';
import { FindingLocation, findingLocationSchema } from './findingLocation.js';
import {
  FindingRepository,
  findingRepositorySchema,
} from './findingRepository.js';
import { FindingRule, findingRuleSchema } from './findingRule.js';
import {
  FixRecommendation,
  fixRecommendationSchema,
} from './fixRecommendation.js';
import { FoundDependency, foundDependencySchema } from './foundDependency.js';
import { Reachability, reachabilitySchema } from './reachability.js';
import { ReviewComment, reviewCommentSchema } from './reviewComment.js';
import { Severity1, severity1Schema } from './severity1.js';
import { State, stateSchema } from './state.js';
import { Status, statusSchema } from './status.js';
import { TriageReason, triageReasonSchema } from './triageReason.js';
import { TriageState, triageStateSchema } from './triageState.js';
import { Usage, usageSchema } from './usage.js';

/** A Supply Chain finding that Semgrep has identified in your organization */
export interface ScaFinding {
  /** The categories of the finding as classified by the associated rule metadata */
  categories?: string[];
  /** Confidence of the finding, derived from the rule that triggered it */
  confidence?: Confidence1;
  /** The timestamp when this finding was created */
  createdAt?: string;
  /** The score assigned by FIRST.org's Exploitation Probability Scoring System */
  epssScore?: EpssScore;
  /** External ticket associated with finding */
  externalTicket?: ExternalTicket;
  /** Unique ID of the Semgrep scan that first identified this finding */
  firstSeenScanId?: bigint;
  /** Recommendations for fixing the vulnerability */
  fixRecommendations?: FixRecommendation[];
  /** Information about the vulnerable package that was found in the codebase */
  foundDependency?: FoundDependency;
  /** Unique ID of this finding */
  id?: bigint;
  /** True if the finding is from a malicious dependency */
  isMalicious?: boolean;
  /** The source URL including file and line number */
  lineOfCodeUrl?: string;
  /** Location of the record in a file, as reported by Semgrep. If null, then the information does not exist or lacks integrity (older or broken scans) */
  location?: FindingLocation;
  /** ID calculated based on a finding's file path, rule identifier and pattern, and index */
  matchBasedId?: string;
  /** Indicates whether the vulnerable code is reachable */
  reachability?: Reachability;
  /** Description of the condition under which the vulnerability becomes reachable. Applies to conditionally reachable findings */
  reachableCondition?: string;
  /** External reference to the source of this finding (e.g. PR) */
  ref?: string;
  /** The timestamp when this finding was detected by Semgrep (the first time, or when reintroduced) */
  relevantSince?: string;
  /** Which repository this finding was identified in */
  repository?: FindingRepository;
  /** List of external review comment information associated with a finding */
  reviewComments?: ReviewComment[];
  /** Rule that applies to this finding */
  rule?: FindingRule;
  /** Deprecated in favor of rule.message. Rule message at the time of finding identification. Older findings may not have a value for this field */
  ruleMessage?: string;
  /** Deprecated in favor of rule.name */
  ruleName?: string;
  /** Severity of the finding, derived from the rule that triggered it. Low is equivalent to INFO, Medium to WARNING, and High to ERROR */
  severity?: Severity1;
  /** The finding's resolution state. Managed only by changes detected at scan time, the `state` is combined with `triage_state` to ultimately determine a final `status` which is exposed in the UI and API */
  state?: State;
  /** When this issue's `state` (resolution state) was last updated, as distinct from when the issue was triaged (`triaged_at`) */
  stateUpdatedAt?: string;
  /** The finding's status as exposed in the UI. Status is a derived property combining information from the finding `state` and `triage_state`. The `triage_state` can be used to override the scan state if the finding is still detected */
  status?: Status;
  /** ID calculated based on a finding's file path, rule identifier and matched code, and index. Prefer `match_based_id` */
  syntacticId?: string;
  /** The detailed comment provided during triage */
  triageComment?: string;
  /** Reason provided when this issue was triaged */
  triageReason?: TriageReason;
  /** The finding's triage state. Note: "reviewing" and "fixing" are only in private beta. Set by the user and used along with state to generate the final "status" viewable in the UI */
  triageState?: TriageState;
  /** When the finding was triaged */
  triagedAt?: string;
  /** Usage of the vulnerable package in the codebase. Applies to reachable findings */
  usage?: Usage;
  /** Identifier of the vulnerability in the vulnerability database */
  vulnerabilityIdentifier?: string;
  additionalProperties?: Record<string, unknown>;
}

export const scaFindingSchema: Schema<ScaFinding> = lazy(() =>
  typedExpandoObject(
    {
      categories: ['categories', optional(array(string()))],
      confidence: ['confidence', optional(confidence1Schema)],
      createdAt: ['created_at', optional(string())],
      epssScore: ['epss_score', optional(epssScoreSchema)],
      externalTicket: ['external_ticket', optional(externalTicketSchema)],
      firstSeenScanId: ['first_seen_scan_id', optional(bigint())],
      fixRecommendations: [
        'fix_recommendations',
        optional(array(fixRecommendationSchema)),
      ],
      foundDependency: ['found_dependency', optional(foundDependencySchema)],
      id: ['id', optional(bigint())],
      isMalicious: ['is_malicious', optional(boolean())],
      lineOfCodeUrl: ['line_of_code_url', optional(string())],
      location: ['location', optional(findingLocationSchema)],
      matchBasedId: ['match_based_id', optional(string())],
      reachability: ['reachability', optional(reachabilitySchema)],
      reachableCondition: ['reachable_condition', optional(string())],
      ref: ['ref', optional(string())],
      relevantSince: ['relevant_since', optional(string())],
      repository: ['repository', optional(findingRepositorySchema)],
      reviewComments: ['review_comments', optional(array(reviewCommentSchema))],
      rule: ['rule', optional(findingRuleSchema)],
      ruleMessage: ['rule_message', optional(string())],
      ruleName: ['rule_name', optional(string())],
      severity: ['severity', optional(severity1Schema)],
      state: ['state', optional(stateSchema)],
      stateUpdatedAt: ['state_updated_at', optional(string())],
      status: ['status', optional(statusSchema)],
      syntacticId: ['syntactic_id', optional(string())],
      triageComment: ['triage_comment', optional(string())],
      triageReason: ['triage_reason', optional(triageReasonSchema)],
      triageState: ['triage_state', optional(triageStateSchema)],
      triagedAt: ['triaged_at', optional(string())],
      usage: ['usage', optional(usageSchema)],
      vulnerabilityIdentifier: ['vulnerability_identifier', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
