/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ScmType
 */
export enum ScmType {
  ScmTypeGithub = 'SCM_TYPE_GITHUB',
  ScmTypeGithubEnterprise = 'SCM_TYPE_GITHUB_ENTERPRISE',
  ScmTypeGitlab = 'SCM_TYPE_GITLAB',
  ScmTypeGitlabSelfmanaged = 'SCM_TYPE_GITLAB_SELFMANAGED',
  ScmTypeBitbucket = 'SCM_TYPE_BITBUCKET',
  ScmTypeBitbucketDatacenter = 'SCM_TYPE_BITBUCKET_DATACENTER',
  ScmTypeAzureDevops = 'SCM_TYPE_AZURE_DEVOPS',
  ScmTypeUnknown = 'SCM_TYPE_UNKNOWN',
  ScmTypeHarness = 'SCM_TYPE_HARNESS',
}

/**
 * Schema for ScmType
 */
export const scmTypeSchema: Schema<ScmType> = stringEnum(ScmType);
