/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { FloatRange, floatRangeSchema } from './floatRange.js';
import { Products, productsSchema } from './products.js';
import { Statuses, statusesSchema } from './statuses.js';

export interface SearchScansRequest {
  /** Only get scans from the specified branch */
  branch?: string;
  /** Cursor to paginate through the results */
  cursor?: string;
  /** Deployment ID (numeric). Example: `123`. Can be found at `/deployments`, or in your Settings in the web UI. */
  deploymentId: string;
  /** Only get scans that are full scans (if false, only get diff scans) */
  isFullScan?: number;
  /** Page size to paginate through the results (default is 100, max is 500) */
  limit?: number;
  /**
   * Only get scans that have these enabled products
   * | value | description |
   * |-------|---------------|
   * | PRODUCT_SAST |  |
   * | PRODUCT_SCA |  |
   * | PRODUCT_SECRETS |  |
   * | PRODUCT_AI_SAST |  |
   */
  products?: Products;
  /** Only get scans for this repo */
  repositoryId?: number;
  /** Only get scans created after this time. Provide time in ISO 8601 format. */
  since?: string;
  /**
   * Only get scans that have one of these statuses
   * | value | description |
   * |-------|---------------|
   * | SCAN_STATUS_RUNNING | The scan is currently running |
   * | SCAN_STATUS_COMPLETED | The scan has completed successfully (0 or 1 exit code) |
   * | SCAN_STATUS_PENDING | The scan is queued and waiting to start |
   * | SCAN_STATUS_CANCELLED | The scan was cancelled before completion |
   * | SCAN_STATUS_ERROR | The scan has exited with a failure (exit code not 0 or 1) |
   * | SCAN_STATUS_NEVER_FINISHED | The scan did not report an error or success after over an hour |
   */
  statuses?: Statuses;
  totalTime?: FloatRange;
  additionalProperties?: Record<string, unknown>;
}

export const searchScansRequestSchema: Schema<SearchScansRequest> = lazy(() =>
  typedExpandoObject(
    {
      branch: ['branch', optional(string())],
      cursor: ['cursor', optional(string())],
      deploymentId: ['deploymentId', string()],
      isFullScan: ['is_full_scan', optional(number())],
      limit: ['limit', optional(number())],
      products: ['products', optional(productsSchema)],
      repositoryId: ['repository_id', optional(number())],
      since: ['since', optional(string())],
      statuses: ['statuses', optional(statusesSchema)],
      totalTime: ['total_time', optional(floatRangeSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
