/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Severity4
 */
export enum Severity4 {
  SeverityHigh = 'SEVERITY_HIGH',
  SeverityMedium = 'SEVERITY_MEDIUM',
  SeverityLow = 'SEVERITY_LOW',
  SeverityCritical = 'SEVERITY_CRITICAL',
}

/**
 * Schema for Severity4
 */
export const severity4Schema: Schema<Severity4> = stringEnum(Severity4);
