/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Severity
 */
export enum Severity {
  SeverityHigh = 'SEVERITY_HIGH',
  SeverityMedium = 'SEVERITY_MEDIUM',
  SeverityLow = 'SEVERITY_LOW',
  SeverityCritical = 'SEVERITY_CRITICAL',
}

/**
 * Schema for Severity
 */
export const severitySchema: Schema<Severity> = stringEnum(Severity);
