/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Severity5
 */
export enum Severity5 {
  SeverityUnspecified = 'SEVERITY_UNSPECIFIED',
  SeverityHigh = 'SEVERITY_HIGH',
  SeverityMedium = 'SEVERITY_MEDIUM',
  SeverityLow = 'SEVERITY_LOW',
  SeverityCritical = 'SEVERITY_CRITICAL',
}

/**
 * Schema for Severity5
 */
export const severity5Schema: Schema<Severity5> = stringEnum(Severity5);
