/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Source
 */
export enum Source {
  SourcePro = 'SOURCE_PRO',
  SourceCommunity = 'SOURCE_COMMUNITY',
  SourceCustom = 'SOURCE_CUSTOM',
}

/**
 * Schema for Source
 */
export const sourceSchema: Schema<Source> = stringEnum(Source);
