/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status6
 */
export enum Status6 {
  FindingStatusOpen = 'FINDING_STATUS_OPEN',
  FindingStatusIgnored = 'FINDING_STATUS_IGNORED',
  FindingStatusFixed = 'FINDING_STATUS_FIXED',
  FindingStatusRemoved = 'FINDING_STATUS_REMOVED',
  FindingStatusUnknown = 'FINDING_STATUS_UNKNOWN',
  FindingStatusProvisionallyIgnored = 'FINDING_STATUS_PROVISIONALLY_IGNORED',
}

/**
 * Schema for Status6
 */
export const status6Schema: Schema<Status6> = stringEnum(Status6);
