/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status3
 */
export enum Status3 {
  SbomExportStatusInProgress = 'SBOM_EXPORT_STATUS_IN_PROGRESS',
  SbomExportStatusCompleted = 'SBOM_EXPORT_STATUS_COMPLETED',
  SbomExportStatusFailed = 'SBOM_EXPORT_STATUS_FAILED',
}

/**
 * Schema for Status3
 */
export const status3Schema: Schema<Status3> = stringEnum(Status3);
