/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Status
 */
export enum Status {
  Open = 'open',
  Fixed = 'fixed',
  Ignored = 'ignored',
  Reviewing = 'reviewing',
  Fixing = 'fixing',
  ProvisionallyIgnored = 'provisionally_ignored',
}

/**
 * Schema for Status
 */
export const statusSchema: Schema<Status> = stringEnum(Status);
