/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Statuses
 */
export enum Statuses {
  ScanStatusUnspecified = 'SCAN_STATUS_UNSPECIFIED',
  ScanStatusRunning = 'SCAN_STATUS_RUNNING',
  ScanStatusCompleted = 'SCAN_STATUS_COMPLETED',
  ScanStatusPending = 'SCAN_STATUS_PENDING',
  ScanStatusCancelled = 'SCAN_STATUS_CANCELLED',
  ScanStatusError = 'SCAN_STATUS_ERROR',
  ScanStatusNeverFinished = 'SCAN_STATUS_NEVER_FINISHED',
}

/**
 * Schema for Statuses
 */
export const statusesSchema: Schema<Statuses> = stringEnum(Statuses);
