/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for State
 */
export enum State {
  Fixed = 'fixed',
  Muted = 'muted',
  Unresolved = 'unresolved',
}

/**
 * Schema for State
 */
export const stateSchema: Schema<State> = stringEnum(State);
