/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ProtosOpenapiV1DiffScan,
  protosOpenapiV1DiffScanSchema,
} from './protosOpenapiV1DiffScan.js';
import {
  ProtosOpenapiV1FullScan,
  protosOpenapiV1FullScanSchema,
} from './protosOpenapiV1FullScan.js';

export interface ToggleProjectManagedScanRequest {
  /** Slug of the deployment name. Can be found at `/deployments`, or in your Settings in the web UI. */
  deploymentSlug: string;
  diffScan?: ProtosOpenapiV1DiffScan;
  fullScan?: ProtosOpenapiV1FullScan;
  /** Name of the project, typically the repository formatted as a path. */
  projectName: string;
  additionalProperties?: Record<string, unknown>;
}

export const toggleProjectManagedScanRequestSchema: Schema<ToggleProjectManagedScanRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        deploymentSlug: ['deploymentSlug', string()],
        diffScan: ['diff_scan', optional(protosOpenapiV1DiffScanSchema)],
        fullScan: ['full_scan', optional(protosOpenapiV1FullScanSchema)],
        projectName: ['projectName', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
