/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Transitivities
 */
export enum Transitivities {
  Direct = 'direct',
  Transitive = 'transitive',
  Unknown = 'unknown',
}

/**
 * Schema for Transitivities
 */
export const transitivitiesSchema: Schema<Transitivities> = stringEnum(
  Transitivities
);
