/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Transitivity2
 */
export enum Transitivity2 {
  Direct = 'direct',
  Transitive = 'transitive',
  Unknown = 'unknown',
}

/**
 * Schema for Transitivity2
 */
export const transitivity2Schema: Schema<Transitivity2> = stringEnum(
  Transitivity2
);
