/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Transitivity
 */
export enum Transitivity {
  UnknownTransitivity = 'UNKNOWN_TRANSITIVITY',
  Transitive = 'TRANSITIVE',
  Direct = 'DIRECT',
}

/**
 * Schema for Transitivity
 */
export const transitivitySchema: Schema<Transitivity> = stringEnum(
  Transitivity
);
