/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Transitivities2
 */
export enum Transitivities2 {
  Direct = 'direct',
  Transitive = 'transitive',
  Unknown = 'unknown',
}

/**
 * Schema for Transitivities2
 */
export const transitivities2Schema: Schema<Transitivities2> = stringEnum(
  Transitivities2
);
