/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Transitivity1
 */
export enum Transitivity1 {
  UnknownTransitivity = 'UNKNOWN_TRANSITIVITY',
  Transitive = 'TRANSITIVE',
  Direct = 'DIRECT',
}

/**
 * Schema for Transitivity1
 */
export const transitivity1Schema: Schema<Transitivity1> = stringEnum(
  Transitivity1
);
