/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TriageState
 */
export enum TriageState {
  Untriaged = 'untriaged',
  Ignored = 'ignored',
  Reopened = 'reopened',
  Reviewing = 'reviewing',
  Fixing = 'fixing',
  ProvisionallyIgnored = 'provisionally_ignored',
}

/**
 * Schema for TriageState
 */
export const triageStateSchema: Schema<TriageState> = stringEnum(TriageState);
