/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TriageReasons2
 */
export enum TriageReasons2 {
  AcceptableRisk = 'acceptable_risk',
  FalsePositive = 'false_positive',
  NoTime = 'no_time',
  NoTriageReason = 'no_triage_reason',
  Duplicate = 'duplicate',
}

/**
 * Schema for TriageReasons2
 */
export const triageReasons2Schema: Schema<TriageReasons2> = stringEnum(
  TriageReasons2
);
