/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Unlink ticket request */
export interface UnlinkTicketRequest {
  /** Deployment ID. Can be found at /deployments, or in your Settings in the web UI. */
  deploymentId: string;
  /** An array of Semgrep finding IDs to unlink tickets from. */
  issueIds: string[];
  additionalProperties?: Record<string, unknown>;
}

export const unlinkTicketRequestSchema: Schema<UnlinkTicketRequest> = typedExpandoObject(
  {
    deploymentId: ['deploymentId', string()],
    issueIds: ['issue_ids', array(string())],
  },
  'additionalProperties',
  optional(unknown())
);
