/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PolicyMode3, policyMode3Schema } from './policyMode3.js';

export interface UpdatePolicyRequest {
  /** Deployment ID (numeric). Example: `123`. Can be found at `/deployments`, or in your Settings in the web UI. */
  deploymentId: string;
  /** Policy ID (numeric). Example: `456`. Can be found at `/deployments/{deploymentId}/policies`. */
  policyId: string;
  /**
   * New policy mode to set for the Rule.
   *  - MODE_MONITOR: Monitor mode, silently report findings
   *  - MODE_COMMENT: Comment mode, leaves PR comments but does not block
   *  - MODE_BLOCK: Block mode, leaves PR comments and blocks PR
   *  - MODE_DISABLED: Disabled mode, not active
   * | value | description |
   * |-------|---------------|
   * | MODE_MONITOR | Monitor mode, silently report findings |
   * | MODE_COMMENT | Comment mode, leaves PR comments but does not block |
   * | MODE_BLOCK | Block mode, leaves PR comments and blocks PR |
   * | MODE_DISABLED | Disabled mode, not active |
   */
  policyMode: PolicyMode3;
  /** Full path of the Rule. */
  rulePath: string;
  additionalProperties?: Record<string, unknown>;
}

export const updatePolicyRequestSchema: Schema<UpdatePolicyRequest> = typedExpandoObject(
  {
    deploymentId: ['deploymentId', string()],
    policyId: ['policyId', string()],
    policyMode: ['policyMode', policyMode3Schema],
    rulePath: ['rulePath', string()],
  },
  'additionalProperties',
  optional(unknown())
);
