/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ManagedScanConfig,
  managedScanConfigSchema,
} from './managedScanConfig.js';

export interface UpdateProjectRequest {
  /** Slug of the deployment name. Can be found at `/deployments`, or in your Settings in the web UI. */
  deploymentSlug: string;
  /** [Beta] Configuration of Semgrep Managed Scans for the project, if relevant. */
  managedScanConfig?: ManagedScanConfig;
  /** The full name of the branch you would like to set as primary. Use "None" if default_branch is known and you wish to set primary to always be the default branch. */
  primaryBranch?: string;
  /** Name of the project, typically the repository formatted as a path. */
  projectName: string;
  /** Tags associated to this project. */
  tags?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const updateProjectRequestSchema: Schema<UpdateProjectRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        deploymentSlug: ['deploymentSlug', string()],
        managedScanConfig: [
          'managed_scan_config',
          optional(managedScanConfigSchema),
        ],
        primaryBranch: ['primary_branch', optional(string())],
        projectName: ['projectName', string()],
        tags: ['tags', optional(array(string()))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
