/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ExternalTicket, externalTicketSchema } from './externalTicket.js';
import { FindingLocation, findingLocationSchema } from './findingLocation.js';

/** Usage of the vulnerable package in the codebase. Applies to reachable findings */
export interface Usage {
  /** External ticket associated with finding */
  externalTicket?: ExternalTicket;
  /** Location of the record in a file, as reported by Semgrep. If null, then the information does not exist or lacks integrity (older or broken scans) */
  location?: FindingLocation;
  additionalProperties?: Record<string, unknown>;
}

export const usageSchema: Schema<Usage> = lazy(() =>
  typedExpandoObject(
    {
      externalTicket: ['external_ticket', optional(externalTicketSchema)],
      location: ['location', optional(findingLocationSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
