/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ValidationState
 */
export enum ValidationState {
  ConfirmedValid = 'confirmed_valid',
  ConfirmedInvalid = 'confirmed_invalid',
  ValidationError = 'validation_error',
  NoValidator = 'no_validator',
}

/**
 * Schema for ValidationState
 */
export const validationStateSchema: Schema<ValidationState> = stringEnum(
  ValidationState
);
