/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ValidationState2
 */
export enum ValidationState2 {
  ValidationStateConfirmedValid = 'VALIDATION_STATE_CONFIRMED_VALID',
  ValidationStateConfirmedInvalid = 'VALIDATION_STATE_CONFIRMED_INVALID',
  ValidationStateValidationError = 'VALIDATION_STATE_VALIDATION_ERROR',
  ValidationStateNoValidator = 'VALIDATION_STATE_NO_VALIDATOR',
}

/**
 * Schema for ValidationState2
 */
export const validationState2Schema: Schema<ValidationState2> = stringEnum(
  ValidationState2
);
