/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ValidationState3
 */
export enum ValidationState3 {
  ValidationStateUnspecified = 'VALIDATION_STATE_UNSPECIFIED',
  ValidationStateConfirmedValid = 'VALIDATION_STATE_CONFIRMED_VALID',
  ValidationStateConfirmedInvalid = 'VALIDATION_STATE_CONFIRMED_INVALID',
  ValidationStateValidationError = 'VALIDATION_STATE_VALIDATION_ERROR',
  ValidationStateNoValidator = 'VALIDATION_STATE_NO_VALIDATOR',
}

/**
 * Schema for ValidationState3
 */
export const validationState3Schema: Schema<ValidationState3> = stringEnum(
  ValidationState3
);
