/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Verdict1
 */
export enum Verdict1 {
  FalsePositive = 'false_positive',
  TruePositive = 'true_positive',
}

/**
 * Schema for Verdict1
 */
export const verdict1Schema: Schema<Verdict1> = stringEnum(Verdict1);
