/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Verdict
 */
export enum Verdict {
  VerdictTruePositive = 'VERDICT_TRUE_POSITIVE',
  VerdictFalsePositive = 'VERDICT_FALSE_POSITIVE',
  VerdictNoVerdict = 'VERDICT_NO_VERDICT',
}

/**
 * Schema for Verdict
 */
export const verdictSchema: Schema<Verdict> = stringEnum(Verdict);
