/**
 * Semgrep Web AppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Visibility
 */
export enum Visibility {
  RepositoryVisibilityPublic = 'REPOSITORY_VISIBILITY_PUBLIC',
  RepositoryVisibilityPrivate = 'REPOSITORY_VISIBILITY_PRIVATE',
  RepositoryVisibilityUnknown = 'REPOSITORY_VISIBILITY_UNKNOWN',
}

/**
 * Schema for Visibility
 */
export const visibilitySchema: Schema<Visibility> = stringEnum(Visibility);
